import React, { createContext, useContext, useEffect, ReactNode } from 'react';
import { useEnhancedUserSettings } from '@/hooks/useEnhancedUserSettings';

interface LanguageContextType {
  currentLanguage: string;
  t: (key: string, defaultValue?: string) => string;
  changeLanguage: (language: string) => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionaries
const translations: Record<string, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.library': 'Library',
    'nav.favorites': 'Favorites',
    'nav.customize': 'Customize',
    'nav.settings': 'Settings',
    
    // Home page
    'home.title': 'Daily Islamic Inspiration',
    'home.subtitle': 'Beautiful Quranic verses as wallpapers',
    'home.todayVerse': "Today's Verse",
    'home.generateWallpaper': 'Generate Wallpaper',
    'home.addToFavorites': 'Add to Favorites',
    'home.removeFromFavorites': 'Remove from Favorites',
    'home.welcomeBack': 'Welcome back, {name}!',
    'home.signInCta': 'Sign in to save your preferences',
    
    // Library
    'library.title': 'Verse Library',
    'library.subtitle': 'Explore our collection of Quranic verses',
    'library.search': 'Search verses...',
    'library.filter': 'Filter by theme',
    'library.all': 'All',
    'library.share': 'Share',
    'library.generateWallpaper': 'Generate Wallpaper',
    'library.noResults': 'No verses found matching your criteria',
    
    // Categories
    'categories.faith': 'Faith',
    'categories.guidance': 'Guidance',
    'categories.comfort': 'Comfort',
    'categories.gratitude': 'Gratitude',
    'categories.protection': 'Protection',
    'categories.trust': 'Trust',
    'categories.power': 'Power',
    'categories.blessing': 'Blessing',
    
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Customize your Ayah Wallpaper experience',
    'settings.account': 'Account',
    'settings.appearance': 'Appearance',
    'settings.language': 'Language & Localization',
    'settings.notifications': 'Notifications',
    'settings.privacy': 'Data & Privacy',
    
    // Language Settings
    'language.interfaceLanguage': 'Interface Language',
    'language.interfaceLanguageDesc': 'Choose your preferred language for the app interface',
    'language.translationStyle': 'Translation Style',
    'language.translationStyleDesc': 'Choose how you prefer Quranic verses to be translated',
    'language.arabicTextSettings': 'Arabic Text Settings',
    'language.arabicTextSize': 'Arabic Text Size',
    'language.regionalSettings': 'Regional Settings',
    'language.dateFormat': 'Date Format',
    'language.timeFormat': 'Time Format',
    'language.unsavedChanges': 'You have unsaved changes',
    'language.discard': 'Discard',
    'language.saveChanges': 'Save changes',
    'language.saving': 'Saving...',
    
    // Translation styles
    'translation.literal': 'Literal Translation',
    'translation.interpretive': 'Interpretive Translation',
    'translation.simplified': 'Simplified Language',
    
    // Date/Time formats
    'format.gregorian': 'Gregorian Calendar',
    'format.hijri': 'Hijri Calendar',
    'format.both': 'Both Calendars',
    'format.12h': '12 Hour (AM/PM)',
    'format.24h': '24 Hour',
    
    // Account
    'account.displayName': 'Display Name',
    'account.email': 'Email Address',
    'account.verified': 'Verified',
    'account.signOut': 'Sign Out',
    'account.deleteAccount': 'Request Account Deletion',
    'account.profilePicture': 'Profile Picture',
    'account.profilePictureHint': 'Add a photo to personalize your account',
    'account.enterDisplayName': 'Enter your display name',
    'account.noDisplayName': 'No display name set',
    'account.profileUpdated': 'Profile updated',
    'account.profileUpdateSuccess': 'Your display name has been updated successfully.',
    'account.profileUpdateError': 'Failed to update profile. Please try again.',
    'account.signedOut': 'Signed out',
    'account.signedOutSuccess': 'You have been successfully signed out.',
    'account.photoUploadSoon': 'Profile picture upload will be available soon!',
    'account.emailChangeNote': 'Email changes require verification and will be available soon',
    'account.contactSupport': 'Contact Support',
    'account.deletionRequest': 'Please email us at support@ayahwallpapers.com for account deletion requests.',
    
    // Daily Verse Settings
    'daily.title': 'Daily Verse Settings',
    'daily.signInNote': 'Sign in to save your daily verse preferences and sync across devices.',
    'daily.updates': 'Daily Verse Updates',
    'daily.updatesDesc': 'Automatically get a new verse each day',
    'daily.updateTime': 'Daily Update Time',
    'daily.updateTimeDesc': 'Choose when to receive your daily verse',
    'daily.selectTime': 'Select time',
    'daily.autoWallpaper': 'Auto-Download Wallpaper',
    'daily.autoWallpaperDesc': 'Automatically download new wallpapers for easy setting',
    'daily.notifications': 'Daily Verse Notifications',
    'daily.notificationsDesc': 'Get notified when your daily verse is ready',
    'daily.frequency': 'Update Frequency',
    'daily.frequencyDesc': 'How often to automatically update your verses',
    'daily.daily': 'Daily',
    'daily.weekly': 'Weekly',
    'daily.manual': 'Manual Only',
    'daily.selectFrequency': 'Select frequency',
    'daily.settingUpdated': 'Setting updated',
    
    // Appearance Settings
    'appearance.title': 'Appearance',
    'appearance.signInNote': 'Sign in to save your appearance preferences across devices.',
    'appearance.fontSize': 'Font Size',
    'appearance.fontSizeSmall': 'Small',
    'appearance.fontSizeMedium': 'Medium (Default)',
    'appearance.fontSizeLarge': 'Large',
    'appearance.fontSizeExtraLarge': 'Extra Large',
    'appearance.selectFontSize': 'Select font size',
    'appearance.previewText': 'Preview: Sample text in {size} size - Lorem ipsum dolor sit amet',
    'appearance.updated': 'Appearance updated',
    
    // Notification Settings
    'notifications.title': 'Notifications',
    'notifications.signInNote': 'Sign in to save your notification preferences across devices.',
    'notifications.enablePush': 'Enable Push Notifications',
    'notifications.enablePushDesc': 'Allow notifications to receive daily verse reminders',
    'notifications.enable': 'Enable',
    'notifications.enabled': 'Notifications enabled',
    'notifications.enabledDesc': 'You\'ll now receive notifications for daily verses and updates.',
    'notifications.blocked': 'Notifications blocked',
    'notifications.blockedDesc': 'Please enable notifications in your browser settings to receive updates.',
    'notifications.notSupported': 'Not supported',
    'notifications.notSupportedDesc': 'Your browser doesn\'t support notifications.',
    'notifications.updated': 'Settings Updated',
    'notifications.settingEnabled': 'Setting enabled successfully',
    'notifications.settingUpdated': 'Setting updated successfully',
    'notifications.permissionGranted': 'Notifications enabled',
    'notifications.permissionGrantedDesc': 'You\'ll now receive notifications for daily verses and updates.',
    'notifications.permissionBlocked': 'Notifications blocked',
    'notifications.permissionBlockedDesc': 'Please enable notifications in your browser settings to receive updates.',
    'notifications.dailyReminders': 'Daily Verse Reminders',
    'notifications.dailyRemindersDesc': 'Get notified when new verses are available',
    'notifications.reminderTime': 'Reminder Time',
    'notifications.selectTime': 'Select notification time',
    'notifications.time6amFajr': '6:00 AM - Fajr',
    'notifications.time7amMorning': '7:00 AM - Morning',
    'notifications.time12pmDhuhr': '12:00 PM - Dhuhr',
    'notifications.time3pmAsr': '3:00 PM - Asr',
    'notifications.time6pmMaghrib': '6:00 PM - Maghrib',
    'notifications.time8pmIsha': '8:00 PM - Isha',
    'notifications.time9pmEvening': '9:00 PM - Evening',
    'notifications.prayerReminders': 'Prayer Time Reminders',
    'notifications.prayerRemindersDesc': 'Get notifications for prayer times with verses',
    'notifications.features': 'New Features & Updates',
    'notifications.featuresDesc': 'Be notified about new app features and improvements',
    'notifications.sound': 'Sound & Vibration',
    'notifications.soundEnabled': 'Notification Sound',
    'notifications.soundEnabledDesc': 'Play sound for notifications',
    'notifications.vibration': 'Vibration',
    'notifications.vibrationDesc': 'Vibrate on mobile devices',
    'notifications.soundSelect': 'Notification Sound',
    'notifications.selectSound': 'Select notification sound',
    'notifications.soundDefault': 'Default',
    'notifications.soundAdhan': 'Adhan Call',
    'notifications.soundChime': 'Gentle Chime',
    'notifications.soundBell': 'Bell',
    'notifications.soundSilent': 'Silent',
    'notifications.quietHours': 'Quiet Hours',
    'notifications.quietHoursDesc': 'Disable notifications during specified hours',
    
    // Data Privacy Settings
    'privacy.title': 'Data & Privacy',
    'privacy.dataSync': 'Data Synchronization',
    'privacy.dataSyncDesc': 'Sync your settings and favorites across devices',
    'privacy.dataSyncDisabled': 'Sign in to enable data sync',
    'privacy.enabled': 'Enabled',
    'privacy.disabled': 'Disabled',
    'privacy.lastSync': 'Last sync:',
    'privacy.syncNow': 'Sync Now',
    'privacy.syncing': 'Syncing...',
    'privacy.storage': 'Storage Usage',
    'privacy.used': 'Used:',
    'privacy.wallpapers': 'Wallpapers:',
    'privacy.settings': 'Settings:',
    'privacy.favorites': 'Favorites:',
    'privacy.cache': 'Cache:',
    'privacy.dataManagement': 'Data Management',
    'privacy.exportData': 'Export My Data',
    'privacy.clearCache': 'Clear Cache & Temporary Files',
    'privacy.clearingCache': 'Clearing Cache...',
    'privacy.signInToExport': 'Sign in to access data export and sync features',
    'privacy.privacyControls': 'Privacy Controls',
    'privacy.analytics': 'Anonymous Analytics',
    'privacy.analyticsDesc': 'Help improve the app by sharing anonymous usage data',
    'privacy.crashReports': 'Crash Reports',
    'privacy.crashReportsDesc': 'Send crash reports to help us fix issues',
    'privacy.legal': 'Legal & Privacy',
    'privacy.privacyPolicy': 'Privacy Policy',
    'privacy.termsOfService': 'Terms of Service',
    'privacy.dataPolicy': 'Data Usage Policy',
    'privacy.dangerZone': 'Danger Zone',
    'privacy.deleteAccount': 'Delete Account',
    'privacy.deleteAccountDesc': 'Permanently delete your account and all associated data. This action cannot be undone.',
    'privacy.requestDeletion': 'Request Account Deletion',
    'privacy.syncSuccess': 'Data synced successfully',
    'privacy.syncSuccessDesc': 'Your preferences and favorites are now up to date across all devices.',
    'privacy.syncFailed': 'Sync failed',
    'privacy.syncFailedDesc': 'There was an error syncing your data. Please try again.',
    'privacy.cacheCleared': 'Cache cleared',
    'privacy.cacheClearedDesc': 'App cache and temporary data have been cleared successfully.',
    'privacy.cacheClearError': 'Failed to clear cache. Please try again.',
    'privacy.dataExported': 'Data exported',
    'privacy.dataExportedDesc': 'Your data has been downloaded to your device.',
    'privacy.analyticsEnabled': 'Analytics enabled',
    'privacy.analyticsDisabled': 'Analytics disabled',
    'privacy.analyticsEnabledDesc': 'Thank you for helping us improve the app!',
    'privacy.analyticsDisabledDesc': 'Analytics have been disabled.',
    'privacy.crashEnabled': 'Crash reporting enabled',
    'privacy.crashDisabled': 'Crash reporting disabled',
    'privacy.crashEnabledDesc': 'We\'ll receive crash reports to improve app stability.',
    'privacy.crashDisabledDesc': 'Crash reporting has been disabled.',
    'privacy.comingSoon': 'Coming Soon',
    'privacy.policyComingSoon': 'Privacy policy will be available soon.',
    'privacy.termsComingSoon': 'Terms of service will be available soon.',
    'privacy.dataComingSoon': 'Data policy will be available soon.',
    
    // Widget Settings
    'widget.title': 'Home Screen Widget',
    'widget.preview': 'Widget Preview',
    'widget.todayVerse': 'Today\'s Verse',
    'widget.enable': 'Enable Widget',
    'widget.enableDesc': 'Show daily verses on your home screen',
    'widget.size': 'Widget Size',
    'widget.sizeSmall': 'Small (2×2) - Arabic only',
    'widget.sizeMedium': 'Medium (4×2) - Arabic + Translation',
    'widget.sizeLarge': 'Large (4×4) - Full verse display',
    'widget.selectSize': 'Select widget size',
    'widget.frequency': 'Update Frequency',
    'widget.frequencyDaily': 'Daily (Recommended)',
    'widget.frequencyTwice': 'Twice Daily',
    'widget.frequencyHourly': 'Every Hour',
    'widget.selectFrequency': 'Select update frequency',
    'widget.frequencyNote': 'More frequent updates may impact battery life',
    'widget.theme': 'Widget Theme',
    'widget.themeClassic': 'Classic Green & Gold',
    'widget.themeMinimal': 'Minimal Dark',
    'widget.themeElegant': 'Elegant Teal',
    'widget.selectTheme': 'Select widget theme',
    'widget.content': 'Content Display',
    'widget.showArabic': 'Show Arabic Text',
    'widget.showArabicDesc': 'Display original Arabic verse',
    'widget.showTranslation': 'Show Translation',
    'widget.showTranslationDesc': 'Display English translation',
    'widget.saveConfig': 'Save Configuration',
    'widget.installWidget': 'Install Widget',
    'widget.configured': 'Widget configured',
    'widget.configuredDesc': 'Your home screen widget settings have been saved',
    'widget.installation': 'Widget installation',
    'widget.installationDesc': 'Please add the Ayah Widget from your device\'s widget gallery',
    'widget.instructionsTitle': 'Installation Instructions',
    'widget.instructionsIOS': 'iOS: Long press on home screen → Add Widget → Search "Ayah Wallpapers"',
    'widget.instructionsAndroid': 'Android: Long press on home screen → Widgets → Find "Daily Verse Widget"',
    'widget.tip': '💡 Tip: Place the widget where you\'ll see it first thing in the morning for daily inspiration',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.surah': 'Surah',
    'common.wallpaper': 'Wallpaper',
    
    // Customize
    'customize.title': 'Customize Wallpaper',
    'customize.subtitle': 'Create your perfect Islamic wallpaper design',
    'customize.livePreview': 'Live Preview',
    'customize.reset': 'Reset',
    'customize.generateHint': 'Generate a preview to see your design',
    'customize.generatePreview': 'Generate Preview',
    'customize.generating': 'Generating...',
    'customize.download': 'Download Wallpaper',
    'customize.regenerate': 'Regenerate',
    'customize.sectionTitle': 'Customize Your Wallpaper',
    'customize.resolution': 'Resolution',
    'customize.backgroundImages': 'Background Images',
    'customize.gradient': 'Gradient',
    'customize.hide': 'Hide',
    'customize.customize': 'Customize',
    'customize.showOriginal': 'Show Original',
    
    // Wallpaper
    'wallpaper.newVerse': 'New Verse',
    'wallpaper.downloaded': 'Wallpaper downloaded',
    'wallpaper.savedToDevice': 'Your beautiful Islamic wallpaper has been saved to your device',
    'wallpaper.generated': 'Wallpaper generated',
    'wallpaper.previewReady': 'Your custom wallpaper preview is ready!',
    'wallpaper.addedToFavorites': 'Added to favorites',
    'wallpaper.savedToFavorites': 'This verse has been saved to your favorites',
    'wallpaper.signInToSave': 'Please sign in to save favorites',
    
    // Favorites
    'favorites.subtitle': 'Your beloved Quranic verses',
    'favorites.noFavoritesYet': 'No favorites yet',
    'favorites.startBuilding': 'Start building your collection by adding verses to your favorites',
    'favorites.browseLibrary': 'Browse Library',
    'favorites.favoriteVerses': 'Favorite Verses',
    'favorites.added': 'Added',
    'favorites.createWallpaper': 'Create Wallpaper',
    'favorites.copiedToClipboard': 'Verse text has been copied to your clipboard',
    'favorites.shareNotSupported': 'Share not supported',
    'favorites.copyManually': 'Please copy the verse text manually',
  },
  
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.library': 'Bibliothèque',
    'nav.favorites': 'Favoris',
    'nav.customize': 'Personnaliser',
    'nav.settings': 'Paramètres',
    
    // Home page
    'home.title': 'Inspiration Islamique Quotidienne',
    'home.subtitle': 'Beaux versets coraniques en fond d\'écran',
    'home.todayVerse': 'Verset du jour',
    'home.generateWallpaper': 'Générer un fond d\'écran',
    'home.addToFavorites': 'Ajouter aux favoris',
    'home.removeFromFavorites': 'Retirer des favoris',
    'home.welcomeBack': 'Bon retour, {name}!',
    'home.signInCta': 'Connectez-vous pour enregistrer vos préférences',
    
    // Library
    'library.title': 'Bibliothèque de versets',
    'library.subtitle': 'Explorez notre collection de versets coraniques',
    'library.search': 'Rechercher des versets...',
    'library.filter': 'Filtrer par thème',
    'library.all': 'Tous',
    'library.share': 'Partager',
    'library.generateWallpaper': 'Générer un fond d\'écran',
    'library.noResults': 'Aucun verset ne correspond à vos critères',
    
    // Catégories
    'categories.faith': 'Foi',
    'categories.guidance': 'Orientation',
    'categories.comfort': 'Réconfort',
    'categories.gratitude': 'Gratitude',
    'categories.protection': 'Protection',
    'categories.trust': 'Confiance',
    'categories.power': 'Puissance',
    'categories.blessing': 'Bénédiction',
    
    // Settings
    'settings.title': 'Paramètres',
    'settings.subtitle': 'Personnalisez votre expérience Ayah Wallpaper',
    'settings.account': 'Compte',
    'settings.appearance': 'Apparence',
    'settings.language': 'Langue et localisation',
    'settings.notifications': 'Notifications',
    'settings.privacy': 'Données et confidentialité',
    
    // Language Settings
    'language.interfaceLanguage': 'Langue de l\'interface',
    'language.interfaceLanguageDesc': 'Choisissez votre langue préférée pour l\'interface de l\'application',
    'language.translationStyle': 'Style de traduction',
    'language.translationStyleDesc': 'Choisissez comment vous préférez que les versets coraniques soient traduits',
    'language.arabicTextSettings': 'Paramètres du texte arabe',
    'language.arabicTextSize': 'Taille du texte arabe',
    'language.regionalSettings': 'Paramètres régionaux',
    'language.dateFormat': 'Format de date',
    'language.timeFormat': 'Format d\'heure',
    'language.unsavedChanges': 'Vous avez des modifications non enregistrées',
    'language.discard': 'Abandonner',
    'language.saveChanges': 'Enregistrer les modifications',
    'language.saving': 'Enregistrement...',
    
    // Translation styles
    'translation.literal': 'Traduction littérale',
    'translation.interpretive': 'Traduction interprétative',
    'translation.simplified': 'Langage simplifié',
    
    // Date/Time formats
    'format.gregorian': 'Calendrier grégorien',
    'format.hijri': 'Calendrier hégirien',
    'format.both': 'Les deux calendriers',
    'format.12h': '12 heures (AM/PM)',
    'format.24h': '24 heures',
    
    // Account
    'account.displayName': 'Nom d\'affichage',
    'account.email': 'Adresse e-mail',
    'account.verified': 'Vérifié',
    'account.signOut': 'Se déconnecter',
    'account.deleteAccount': 'Demander la suppression du compte',
    'account.profilePicture': 'Photo de profil',
    'account.profilePictureHint': 'Ajoutez une photo pour personnaliser votre compte',
    'account.enterDisplayName': 'Entrez votre nom d\'affichage',
    'account.noDisplayName': 'Aucun nom d\'affichage défini',
    'account.profileUpdated': 'Profil mis à jour',
    'account.profileUpdateSuccess': 'Votre nom d\'affichage a été mis à jour avec succès.',
    'account.profileUpdateError': 'Échec de la mise à jour du profil. Veuillez réessayer.',
    'account.signedOut': 'Déconnecté',
    'account.signedOutSuccess': 'Vous avez été déconnecté avec succès.',
    'account.photoUploadSoon': 'Le téléchargement de photo de profil sera bientôt disponible !',
    'account.emailChangeNote': 'Les changements d\'e-mail nécessitent une vérification et seront bientôt disponibles',
    'account.contactSupport': 'Contacter le support',
    'account.deletionRequest': 'Veuillez nous envoyer un e-mail à support@ayahwallpapers.com pour les demandes de suppression de compte.',
    
    // Daily Verse Settings  
    'daily.title': 'Paramètres du verset quotidien',
    'daily.signInNote': 'Connectez-vous pour enregistrer vos préférences de verset quotidien et synchroniser sur tous les appareils.',
    'daily.updates': 'Mises à jour du verset quotidien',
    'daily.updatesDesc': 'Obtenez automatiquement un nouveau verset chaque jour',
    'daily.updateTime': 'Heure de mise à jour quotidienne',
    'daily.updateTimeDesc': 'Choisissez quand recevoir votre verset quotidien',
    'daily.selectTime': 'Sélectionner l\'heure',
    'daily.autoWallpaper': 'Téléchargement automatique de fond d\'écran',
    'daily.autoWallpaperDesc': 'Téléchargez automatiquement de nouveaux fonds d\'écran pour un réglage facile',
    'daily.notifications': 'Notifications de verset quotidien',
    'daily.notificationsDesc': 'Soyez averti lorsque votre verset quotidien est prêt',
    'daily.frequency': 'Fréquence de mise à jour',
    'daily.frequencyDesc': 'À quelle fréquence mettre à jour automatiquement vos versets',
    'daily.daily': 'Quotidien',
    'daily.weekly': 'Hebdomadaire',
    'daily.manual': 'Manuel uniquement',
    'daily.selectFrequency': 'Sélectionner la fréquence',
    'daily.settingUpdated': 'Paramètre mis à jour',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.signInNote': 'Connectez-vous pour enregistrer vos préférences de notification sur tous les appareils.',
    'notifications.enablePush': 'Activer les notifications push',
    'notifications.enablePushDesc': 'Autoriser les notifications pour recevoir les rappels de versets quotidiens',
    'notifications.enable': 'Activer',
    'notifications.enabled': 'Notifications activées',
    'notifications.enabledDesc': 'Vous recevrez maintenant des notifications pour les versets quotidiens et les mises à jour.',
    'notifications.blocked': 'Notifications bloquées',
    'notifications.blockedDesc': 'Veuillez activer les notifications dans les paramètres de votre navigateur pour recevoir les mises à jour.',
    'notifications.notSupported': 'Non pris en charge',
    'notifications.notSupportedDesc': 'Votre navigateur ne prend pas en charge les notifications.',
    'notifications.updated': 'Paramètres mis à jour',
    'notifications.settingEnabled': 'Paramètre activé avec succès',
    'notifications.settingUpdated': 'Paramètre mis à jour avec succès',
    'notifications.permissionGranted': 'Notifications activées',
    'notifications.permissionGrantedDesc': 'Vous recevrez maintenant des notifications pour les versets quotidiens et les mises à jour.',
    'notifications.permissionBlocked': 'Notifications bloquées',
    'notifications.permissionBlockedDesc': 'Veuillez activer les notifications dans les paramètres de votre navigateur pour recevoir les mises à jour.',
    'notifications.dailyReminders': 'Rappels de versets quotidiens',
    'notifications.dailyRemindersDesc': 'Être notifié lorsque de nouveaux versets sont disponibles',
    'notifications.reminderTime': 'Heure du rappel',
    'notifications.selectTime': 'Sélectionner l\'heure de notification',
    'notifications.time6amFajr': '6h00 - Fajr',
    'notifications.time7amMorning': '7h00 - Matin',
    'notifications.time12pmDhuhr': '12h00 - Dhuhr',
    'notifications.time3pmAsr': '15h00 - Asr',
    'notifications.time6pmMaghrib': '18h00 - Maghrib',
    'notifications.time8pmIsha': '20h00 - Isha',
    'notifications.time9pmEvening': '21h00 - Soir',
    'notifications.prayerReminders': 'Rappels d\'heures de prière',
    'notifications.prayerRemindersDesc': 'Recevoir des notifications pour les heures de prière avec des versets',
    'notifications.features': 'Nouvelles fonctionnalités et mises à jour',
    'notifications.featuresDesc': 'Être notifié des nouvelles fonctionnalités de l\'application et des améliorations',
    'notifications.sound': 'Son et vibration',
    'notifications.soundEnabled': 'Son de notification',
    'notifications.soundEnabledDesc': 'Jouer un son pour les notifications',
    'notifications.vibration': 'Vibration',
    'notifications.vibrationDesc': 'Vibrer sur les appareils mobiles',
    'notifications.soundSelect': 'Son de notification',
    'notifications.selectSound': 'Sélectionner le son de notification',
    'notifications.soundDefault': 'Par défaut',
    'notifications.soundAdhan': 'Appel à la prière',
    'notifications.soundChime': 'Carillon doux',
    'notifications.soundBell': 'Cloche',
    'notifications.soundSilent': 'Silencieux',
    'notifications.quietHours': 'Heures silencieuses',
    'notifications.quietHoursDesc': 'Désactiver les notifications pendant les heures spécifiées',
    
    // Common
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.surah': 'Sourate',
    'common.wallpaper': 'Fond',
    
    // Personnaliser
    'customize.title': 'Personnaliser le fond',
    'customize.subtitle': 'Créez votre fond islamique parfait',
    'customize.livePreview': 'Aperçu en direct',
    'customize.reset': 'Réinitialiser',
    'customize.generateHint': 'Générez un aperçu pour voir votre design',
    'customize.generatePreview': 'Générer un aperçu',
    'customize.generating': 'Génération...',
    'customize.download': 'Télécharger le fond',
    'customize.regenerate': 'Régénérer',
    'customize.sectionTitle': 'Personnalisez votre fond',
    'customize.resolution': 'Résolution',
    'customize.backgroundImages': 'Images de fond',
    'customize.gradient': 'Dégradé',
    'customize.hide': 'Masquer',
    'customize.customize': 'Personnaliser',
    'customize.showOriginal': 'Voir l\'original',
    
    // Fond d'écran
    'wallpaper.newVerse': 'Nouveau verset',
    'wallpaper.downloaded': 'Fond téléchargé',
    'wallpaper.savedToDevice': 'Votre beau fond islamique a été enregistré sur votre appareil',
    'wallpaper.generated': 'Fond généré',
    'wallpaper.previewReady': 'Votre aperçu personnalisé est prêt !',
    'wallpaper.addedToFavorites': 'Ajouté aux favoris',
    'wallpaper.savedToFavorites': 'Ce verset a été enregistré dans vos favoris',
    'wallpaper.signInToSave': 'Veuillez vous connecter pour enregistrer les favoris',
    
    // Favoris
    'favorites.subtitle': 'Vos versets coraniques préférés',
    'favorites.noFavoritesYet': 'Aucun favori pour le moment',
    'favorites.startBuilding': 'Commencez à constituer votre collection en ajoutant des versets à vos favoris',
    'favorites.browseLibrary': 'Parcourir la bibliothèque',
    'favorites.favoriteVerses': 'Versets favoris',
    'favorites.added': 'Ajouté',
    'favorites.createWallpaper': 'Créer un fond',
    'favorites.copiedToClipboard': 'Le texte du verset a été copié dans votre presse-papiers',
    'favorites.shareNotSupported': 'Partage non pris en charge',
    'favorites.copyManually': 'Veuillez copier le texte du verset manuellement',
  },
  
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.library': 'المكتبة',
    'nav.favorites': 'المفضلة',
    'nav.customize': 'تخصيص',
    'nav.settings': 'الإعدادات',
    
    // Home page
    'home.title': 'الإلهام الإسلامي اليومي',
    'home.subtitle': 'آيات قرآنية جميلة كخلفيات',
    'home.todayVerse': 'آية اليوم',
    'home.generateWallpaper': 'إنشاء خلفية',
    'home.addToFavorites': 'إضافة إلى المفضلة',
    'home.removeFromFavorites': 'إزالة من المفضلة',
    'home.welcomeBack': 'مرحبًا بعودتك، {name}!',
    'home.signInCta': 'سجّل الدخول لحفظ تفضيلاتك',
    
    // Library
    'library.title': 'مكتبة الآيات',
    'library.subtitle': 'استكشف مجموعتنا من الآيات القرآنية',
    'library.search': 'البحث في الآيات...',
    'library.filter': 'فلترة حسب الموضوع',
    'library.all': 'الكل',
    'library.share': 'مشاركة',
    'library.generateWallpaper': 'إنشاء خلفية',
    'library.noResults': 'لا توجد آيات مطابقة لمعاييرك',
    
    // التصنيفات
    'categories.faith': 'الإيمان',
    'categories.guidance': 'الهداية',
    'categories.comfort': 'السكينة',
    'categories.gratitude': 'الشكر',
    'categories.protection': 'الحماية',
    'categories.trust': 'التوكل',
    'categories.power': 'القدرة',
    'categories.blessing': 'البركة',
    
    // Settings
    'settings.title': 'الإعدادات',
    'settings.subtitle': 'خصص تجربة خلفيات الآيات الخاصة بك',
    'settings.account': 'الحساب',
    'settings.appearance': 'المظهر',
    'settings.language': 'اللغة والموقع',
    'settings.notifications': 'الإشعارات',
    'settings.privacy': 'البيانات والخصوصية',
    
    // Language Settings
    'language.interfaceLanguage': 'لغة الواجهة',
    'language.interfaceLanguageDesc': 'اختر لغتك المفضلة لواجهة التطبيق',
    'language.translationStyle': 'نمط الترجمة',
    'language.translationStyleDesc': 'اختر كيف تفضل ترجمة الآيات القرآنية',
    'language.arabicTextSettings': 'إعدادات النص العربي',
    'language.arabicTextSize': 'حجم النص العربي',
    'language.regionalSettings': 'الإعدادات الإقليمية',
    'language.dateFormat': 'تنسيق التاريخ',
    'language.timeFormat': 'تنسيق الوقت',
    'language.unsavedChanges': 'لديك تغييرات غير محفوظة',
    'language.discard': 'تجاهل',
    'language.saveChanges': 'حفظ التغييرات',
    'language.saving': 'جاري الحفظ...',
    
    // Translation styles
    'translation.literal': 'ترجمة حرفية',
    'translation.interpretive': 'ترجمة تفسيرية',
    'translation.simplified': 'لغة مبسطة',
    
    // Date/Time formats
    'format.gregorian': 'التقويم الميلادي',
    'format.hijri': 'التقويم الهجري',
    'format.both': 'كلا التقويمين',
    'format.12h': '12 ساعة (ص/م)',
    'format.24h': '24 ساعة',
    
    // Account
    'account.displayName': 'اسم العرض',
    'account.email': 'عنوان البريد الإلكتروني',
    'account.verified': 'مُتحقق منه',
    'account.signOut': 'تسجيل الخروج',
    'account.deleteAccount': 'طلب حذف الحساب',
    'account.profilePicture': 'صورة الملف الشخصي',
    'account.profilePictureHint': 'أضف صورة لتخصيص حسابك',
    'account.enterDisplayName': 'أدخل اسم العرض الخاص بك',
    'account.noDisplayName': 'لم يتم تعيين اسم عرض',
    'account.profileUpdated': 'تم تحديث الملف الشخصي',
    'account.profileUpdateSuccess': 'تم تحديث اسم العرض بنجاح.',
    'account.profileUpdateError': 'فشل في تحديث الملف الشخصي. يرجى المحاولة مرة أخرى.',
    'account.signedOut': 'تم تسجيل الخروج',
    'account.signedOutSuccess': 'تم تسجيل خروجك بنجاح.',
    'account.photoUploadSoon': 'سيتوفر رفع صورة الملف الشخصي قريباً!',
    'account.emailChangeNote': 'تتطلب تغييرات البريد الإلكتروني التحقق وستكون متاحة قريباً',
    'account.contactSupport': 'اتصل بالدعم',
    'account.deletionRequest': 'يرجى مراسلتنا على support@ayahwallpapers.com لطلبات حذف الحساب.',
    
    // Notifications
    'notifications.title': 'الإشعارات',
    'notifications.signInNote': 'سجل الدخول لحفظ إعدادات الإشعارات على جميع الأجهزة.',
    'notifications.enablePush': 'تفعيل الإشعارات الفورية',
    'notifications.enablePushDesc': 'السماح بالإشعارات لتلقي تذكيرات الآيات اليومية',
    'notifications.enable': 'تفعيل',
    'notifications.enabled': 'تم تفعيل الإشعارات',
    'notifications.enabledDesc': 'ستتلقى الآن إشعارات للآيات اليومية والتحديثات.',
    'notifications.blocked': 'الإشعارات محظورة',
    'notifications.blockedDesc': 'يرجى تفعيل الإشعارات في إعدادات المتصفح لتلقي التحديثات.',
    'notifications.notSupported': 'غير مدعوم',
    'notifications.notSupportedDesc': 'متصفحك لا يدعم الإشعارات.',
    'notifications.updated': 'تم تحديث الإعدادات',
    'notifications.settingEnabled': 'تم تفعيل الإعداد بنجاح',
    'notifications.settingUpdated': 'تم تحديث الإعداد بنجاح',
    'notifications.permissionGranted': 'تم تفعيل الإشعارات',
    'notifications.permissionGrantedDesc': 'ستتلقى الآن إشعارات للآيات اليومية والتحديثات.',
    'notifications.permissionBlocked': 'الإشعارات محظورة',
    'notifications.permissionBlockedDesc': 'يرجى تفعيل الإشعارات في إعدادات المتصفح لتلقي التحديثات.',
    'notifications.dailyReminders': 'تذكيرات الآيات اليومية',
    'notifications.dailyRemindersDesc': 'تلقي إشعارات عند توفر آيات جديدة',
    'notifications.reminderTime': 'وقت التذكير',
    'notifications.selectTime': 'اختر وقت الإشعار',
    'notifications.time6amFajr': '6:00 ص - الفجر',
    'notifications.time7amMorning': '7:00 ص - الصباح',
    'notifications.time12pmDhuhr': '12:00 م - الظهر',
    'notifications.time3pmAsr': '3:00 م - العصر',
    'notifications.time6pmMaghrib': '6:00 م - المغرب',
    'notifications.time8pmIsha': '8:00 م - العشاء',
    'notifications.time9pmEvening': '9:00 م - المساء',
    'notifications.prayerReminders': 'تذكيرات أوقات الصلاة',
    'notifications.prayerRemindersDesc': 'تلقي إشعارات لأوقات الصلاة مع الآيات',
    'notifications.features': 'الميزات الجديدة والتحديثات',
    'notifications.featuresDesc': 'تلقي إشعارات حول ميزات التطبيق الجديدة والتحسينات',
    'notifications.sound': 'الصوت والاهتزاز',
    'notifications.soundEnabled': 'صوت الإشعار',
    'notifications.soundEnabledDesc': 'تشغيل صوت للإشعارات',
    'notifications.vibration': 'الاهتزاز',
    'notifications.vibrationDesc': 'اهتزاز على الأجهزة المحمولة',
    'notifications.soundSelect': 'صوت الإشعار',
    'notifications.selectSound': 'اختر صوت الإشعار',
    'notifications.soundDefault': 'افتراضي',
    'notifications.soundAdhan': 'نداء الصلاة',
    'notifications.soundChime': 'جرس لطيف',
    'notifications.soundBell': 'جرس',
    'notifications.soundSilent': 'صامت',
    'notifications.quietHours': 'ساعات الصمت',
    'notifications.quietHoursDesc': 'إيقاف الإشعارات خلال الساعات المحددة',
    
    // Common
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجح',
    'common.surah': 'سورة',
    'common.wallpaper': 'خلفية',
    
    // تخصيص
    'customize.title': 'تخصيص الخلفية',
    'customize.subtitle': 'أنشئ خلفيتك الإسلامية المثالية',
    'customize.livePreview': 'معاينة مباشرة',
    'customize.reset': 'إعادة ضبط',
    'customize.generateHint': 'أنشئ معاينة لرؤية تصميمك',
    'customize.generatePreview': 'إنشاء معاينة',
    'customize.generating': 'جارٍ الإنشاء...',
    'customize.download': 'تحميل الخلفية',
    'customize.regenerate': 'إعادة الإنشاء',
    'customize.sectionTitle': 'خصص خلفيتك',
    'customize.resolution': 'الدقة',
    'customize.backgroundImages': 'صور الخلفية',
    'customize.gradient': 'تدرج',
    'customize.hide': 'إخفاء',
    'customize.customize': 'تخصيص',
    'customize.showOriginal': 'عرض الأصل',
    
    // خلفية
    'wallpaper.newVerse': 'آية جديدة',
    'wallpaper.downloaded': 'تم تنزيل الخلفية',
    'wallpaper.savedToDevice': 'تم حفظ الخلفية الإسلامية الجميلة على جهازك',
    'wallpaper.generated': 'تم إنشاء الخلفية',
    'wallpaper.previewReady': 'جاهزة معاينتك المخصصة!',
    'wallpaper.addedToFavorites': 'تمت الإضافة إلى المفضلة',
    'wallpaper.savedToFavorites': 'تم حفظ هذه الآية في المفضلة',
    'wallpaper.signInToSave': 'يرجى تسجيل الدخول لحفظ المفضلة',
    
    // المفضلة
    'favorites.subtitle': 'آياتك القرآنية المحببة',
    'favorites.noFavoritesYet': 'لا توجد مفضلة بعد',
    'favorites.startBuilding': 'ابدأ ببناء مجموعتك بإضافة الآيات إلى المفضلة',
    'favorites.browseLibrary': 'تصفح المكتبة',
    'favorites.favoriteVerses': 'الآيات المفضلة',
    'favorites.added': 'أضيفت',
    'favorites.createWallpaper': 'إنشاء خلفية',
    'favorites.copiedToClipboard': 'تم نسخ نص الآية إلى الحافظة',
    'favorites.shareNotSupported': 'المشاركة غير مدعومة',
    'favorites.copyManually': 'يرجى نسخ نص الآية يدويًا',
  },
  
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.library': 'Biblioteca',
    'nav.favorites': 'Favoritos',
    'nav.customize': 'Personalizar',
    'nav.settings': 'Configuración',
    
    // Home page
    'home.title': 'Inspiración Islámica Diaria',
    'home.subtitle': 'Hermosos versos coránicos como fondos de pantalla',
    'home.todayVerse': 'Verso de hoy',
    'home.generateWallpaper': 'Generar fondo de pantalla',
    'home.addToFavorites': 'Agregar a favoritos',
    'home.removeFromFavorites': 'Quitar de favoritos',
    'home.welcomeBack': '¡Bienvenido de nuevo, {name}!',
    'home.signInCta': 'Inicia sesión para guardar tus preferencias',
    
    // Library
    'library.title': 'Biblioteca de versos',
    'library.subtitle': 'Explora nuestra colección de versos coránicos',
    'library.search': 'Buscar versos...',
    'library.filter': 'Filtrar por tema',
    'library.all': 'Todos',
    'library.share': 'Compartir',
    'library.generateWallpaper': 'Generar fondo de pantalla',
    'library.noResults': 'No se encontraron versos que coincidan con tus criterios',
    
    // Categorías
    'categories.faith': 'Fe',
    'categories.guidance': 'Guía',
    'categories.comfort': 'Consuelo',
    'categories.gratitude': 'Gratitud',
    'categories.protection': 'Protección',
    'categories.trust': 'Confianza',
    'categories.power': 'Poder',
    'categories.blessing': 'Bendición',
    
    // Settings
    'settings.title': 'Configuración',
    'settings.subtitle': 'Personaliza tu experiencia con Ayah Wallpaper',
    'settings.account': 'Cuenta',
    'settings.appearance': 'Apariencia',
    'settings.language': 'Idioma y localización',
    'settings.notifications': 'Notificaciones',
    'settings.privacy': 'Datos y privacidad',
    
    // Language Settings
    'language.interfaceLanguage': 'Idioma de la interfaz',
    'language.interfaceLanguageDesc': 'Elige tu idioma preferido para la interfaz de la aplicación',
    'language.translationStyle': 'Estilo de traducción',
    'language.translationStyleDesc': 'Elige cómo prefieres que se traduzcan los versos coránicos',
    'language.arabicTextSettings': 'Configuración del texto árabe',
    'language.arabicTextSize': 'Tamaño del texto árabe',
    'language.regionalSettings': 'Configuración regional',
    'language.dateFormat': 'Formato de fecha',
    'language.timeFormat': 'Formato de hora',
    'language.unsavedChanges': 'Tienes cambios no guardados',
    'language.discard': 'Descartar',
    'language.saveChanges': 'Guardar cambios',
    'language.saving': 'Guardando...',
    
    // Translation styles
    'translation.literal': 'Traducción literal',
    'translation.interpretive': 'Traducción interpretativa',
    'translation.simplified': 'Lenguaje simplificado',
    
    // Date/Time formats
    'format.gregorian': 'Calendario gregoriano',
    'format.hijri': 'Calendario hijri',
    'format.both': 'Ambos calendarios',
    'format.12h': '12 horas (AM/PM)',
    'format.24h': '24 horas',
    
    // Account
    'account.displayName': 'Nombre para mostrar',
    'account.email': 'Dirección de correo electrónico',
    'account.verified': 'Verificado',
    'account.signOut': 'Cerrar sesión',
    'account.deleteAccount': 'Solicitar eliminación de cuenta',
    'account.profilePicture': 'Foto de perfil',
    'account.profilePictureHint': 'Agrega una foto para personalizar tu cuenta',
    'account.enterDisplayName': 'Ingresa tu nombre para mostrar',
    'account.noDisplayName': 'No se ha establecido nombre para mostrar',
    'account.profileUpdated': 'Perfil actualizado',
    'account.profileUpdateSuccess': 'Tu nombre para mostrar se ha actualizado correctamente.',
    'account.profileUpdateError': 'Error al actualizar el perfil. Inténtalo de nuevo.',
    'account.signedOut': 'Sesión cerrada',
    'account.signedOutSuccess': 'Has cerrado sesión correctamente.',
    'account.photoUploadSoon': '¡La subida de foto de perfil estará disponible pronto!',
    'account.emailChangeNote': 'Los cambios de correo electrónico requieren verificación y estarán disponibles pronto',
    'account.contactSupport': 'Contactar soporte',
    'account.deletionRequest': 'Envíanos un correo a support@ayahwallpapers.com para solicitudes de eliminación de cuenta.',
    
    // Notifications
    'notifications.title': 'Notificaciones',
    'notifications.signInNote': 'Inicia sesión para guardar tus preferencias de notificación en todos los dispositivos.',
    'notifications.enablePush': 'Habilitar notificaciones push',
    'notifications.enablePushDesc': 'Permitir notificaciones para recibir recordatorios de versos diarios',
    'notifications.enable': 'Habilitar',
    'notifications.enabled': 'Notificaciones habilitadas',
    'notifications.enabledDesc': 'Ahora recibirás notificaciones para versos diarios y actualizaciones.',
    'notifications.blocked': 'Notificaciones bloqueadas',
    'notifications.blockedDesc': 'Por favor habilita las notificaciones en la configuración de tu navegador para recibir actualizaciones.',
    'notifications.notSupported': 'No compatible',
    'notifications.notSupportedDesc': 'Tu navegador no soporta notificaciones.',
    'notifications.updated': 'Configuración actualizada',
    'notifications.settingEnabled': 'Configuración habilitada exitosamente',
    'notifications.settingUpdated': 'Configuración actualizada exitosamente',
    'notifications.permissionGranted': 'Notificaciones habilitadas',
    'notifications.permissionGrantedDesc': 'Ahora recibirás notificaciones para versos diarios y actualizaciones.',
    'notifications.permissionBlocked': 'Notificaciones bloqueadas',
    'notifications.permissionBlockedDesc': 'Por favor habilita las notificaciones en la configuración de tu navegador para recibir actualizaciones.',
    'notifications.dailyReminders': 'Recordatorios de versos diarios',
    'notifications.dailyRemindersDesc': 'Recibir notificaciones cuando nuevos versos estén disponibles',
    'notifications.reminderTime': 'Hora de recordatorio',
    'notifications.selectTime': 'Seleccionar hora de notificación',
    'notifications.time6amFajr': '6:00 AM - Fajr',
    'notifications.time7amMorning': '7:00 AM - Mañana',
    'notifications.time12pmDhuhr': '12:00 PM - Dhuhr',
    'notifications.time3pmAsr': '3:00 PM - Asr',
    'notifications.time6pmMaghrib': '6:00 PM - Maghrib',
    'notifications.time8pmIsha': '8:00 PM - Isha',
    'notifications.time9pmEvening': '9:00 PM - Noche',
    'notifications.prayerReminders': 'Recordatorios de horarios de oración',
    'notifications.prayerRemindersDesc': 'Recibir notificaciones para horarios de oración con versos',
    'notifications.features': 'Nuevas características y actualizaciones',
    'notifications.featuresDesc': 'Ser notificado sobre nuevas características de la aplicación y mejoras',
    'notifications.sound': 'Sonido y vibración',
    'notifications.soundEnabled': 'Sonido de notificación',
    'notifications.soundEnabledDesc': 'Reproducir sonido para notificaciones',
    'notifications.vibration': 'Vibración',
    'notifications.vibrationDesc': 'Vibrar en dispositivos móviles',
    'notifications.soundSelect': 'Sonido de notificación',
    'notifications.selectSound': 'Seleccionar sonido de notificación',
    'notifications.soundDefault': 'Predeterminado',
    'notifications.soundAdhan': 'Llamada a la oración',
    'notifications.soundChime': 'Campana suave',
    'notifications.soundBell': 'Campana',
    'notifications.soundSilent': 'Silencioso',
    'notifications.quietHours': 'Horas silenciosas',
    'notifications.quietHoursDesc': 'Deshabilitar notificaciones durante las horas especificadas',
    
    // Common
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.surah': 'Sura',
    'common.wallpaper': 'Fondo',
    
    // Personalizar
    'customize.title': 'Personalizar fondo',
    'customize.subtitle': 'Crea tu fondo islámico perfecto',
    'customize.livePreview': 'Vista previa en vivo',
    'customize.reset': 'Restablecer',
    'customize.generateHint': 'Genera una vista previa para ver tu diseño',
    'customize.generatePreview': 'Generar vista previa',
    'customize.generating': 'Generando...',
    'customize.download': 'Descargar fondo',
    'customize.regenerate': 'Regenerar',
    'customize.sectionTitle': 'Personaliza tu fondo',
    'customize.resolution': 'Resolución',
    'customize.backgroundImages': 'Imágenes de fondo',
    'customize.gradient': 'Degradado',
    'customize.hide': 'Ocultar',
    'customize.customize': 'Personalizar',
    'customize.showOriginal': 'Ver original',
    
    // Fondo de pantalla
    'wallpaper.newVerse': 'Nuevo verso',
    'wallpaper.downloaded': 'Fondo descargado',
    'wallpaper.savedToDevice': 'Tu hermoso fondo islámico se ha guardado en tu dispositivo',
    'wallpaper.generated': 'Fondo generado',
    'wallpaper.previewReady': '¡Tu vista previa personalizada está lista!',
    'wallpaper.addedToFavorites': 'Agregado a favoritos',
    'wallpaper.savedToFavorites': 'Este verso se ha guardado en tus favoritos',
    'wallpaper.signInToSave': 'Inicia sesión para guardar favoritos',
  },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const { settings, updateSettings } = useEnhancedUserSettings();
  
  const t = (key: string, defaultValue?: string): string => {
    const currentTranslations = translations[settings.language] || translations.en;
    return currentTranslations[key] || defaultValue || key;
  };

  const changeLanguage = async (language: string) => {
    await updateSettings({ language });
    
    // Update document direction for RTL languages
    if (language === 'ar') {
      document.documentElement.dir = 'rtl';
      document.documentElement.lang = 'ar';
    } else {
      document.documentElement.dir = 'ltr';
      document.documentElement.lang = language;
    }
  };

  // Set initial direction and language
  useEffect(() => {
    if (settings.language === 'ar') {
      document.documentElement.dir = 'rtl';
      document.documentElement.lang = 'ar';
    } else {
      document.documentElement.dir = 'ltr';
      document.documentElement.lang = settings.language;
    }
  }, [settings.language]);

  return (
    <LanguageContext.Provider value={{
      currentLanguage: settings.language,
      t,
      changeLanguage
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};