import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'ar' | 'fr' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, fallback?: string) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.library': 'Library',
    'nav.favorites': 'Favorites',
    'nav.customize': 'Customize',
    'nav.settings': 'Settings',
    
    // Home page
    'home.title': 'Daily Islamic Inspiration',
    'home.subtitle': 'Beautiful Quranic verses as wallpapers',
    'home.todayVerse': 'Today\'s Verse',
    'home.generateWallpaper': 'Generate Wallpaper',
    'home.addToFavorites': 'Add to Favorites',
    'home.removeFromFavorites': 'Remove from Favorites',
    'home.welcomeBack': 'Welcome back, {name}!',
    'home.signInCta': 'Sign in to save your preferences',
    
    // Library
    'library.title': 'Verse Library',
    'library.subtitle': 'Explore our collection of Quranic verses',
    'library.search': 'Search verses...',
    'library.filter': 'Filter by theme',
    'library.all': 'All',
    'library.share': 'Share',
    'library.generateWallpaper': 'Generate Wallpaper',
    'library.noResults': 'No verses match your search criteria',
    
    // Categories
    'categories.faith': 'Faith',
    'categories.wisdom': 'Wisdom',
    'categories.patience': 'Patience',
    'categories.forgiveness': 'Forgiveness',
    'categories.guidance': 'Guidance',
    'categories.comfort': 'Comfort',
    'categories.gratitude': 'Gratitude',
    'categories.protection': 'Protection',
    'categories.trust': 'Trust',
    'categories.power': 'Power',
    'categories.blessing': 'Blessing',
    
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Customize your Ayah Wallpaper experience',
    'settings.account': 'Account',
    'settings.appearance': 'Appearance',
    'settings.language': 'Language & Localization',
    'settings.notifications': 'Notifications',
    'settings.privacy': 'Data & Privacy',
    
    // Language Settings
    'language.interfaceLanguage': 'Interface Language',
    'language.interfaceLanguageDesc': 'Choose your preferred language for the app interface',
    'language.translationStyle': 'Translation Style',
    'language.translationStyleDesc': 'Choose how you prefer Quranic verses to be translated',
    'language.arabicTextSettings': 'Arabic Text Settings',
    'language.arabicTextSize': 'Arabic Text Size',
    'language.regionalSettings': 'Regional Settings',
    'language.dateFormat': 'Date Format',
    'language.timeFormat': 'Time Format',
    'language.unsavedChanges': 'You have unsaved changes',
    'language.discard': 'Discard',
    'language.saveChanges': 'Save Changes',
    'language.saving': 'Saving...',
    
    // Translation styles
    'translation.literal': 'Literal Translation',
    'translation.interpretive': 'Interpretive Translation',
    'translation.simplified': 'Simplified Language',
    
    // Date/Time formats
    'format.gregorian': 'Gregorian Calendar',
    'format.hijri': 'Hijri Calendar',
    'format.both': 'Both Calendars',
    'format.12h': '12-hour (AM/PM)',
    'format.24h': '24-hour',
    
    // Account
    'account.displayName': 'Display Name',
    'account.email': 'Email Address',
    'account.verified': 'Verified',
    'account.signOut': 'Sign Out',
    'account.deleteAccount': 'Request Account Deletion',
    'account.profilePicture': 'Profile Picture',
    'account.profilePictureHint': 'Add a photo to personalize your account',
    'account.enterDisplayName': 'Enter your display name',
    'account.noDisplayName': 'No display name set',
    'account.profileUpdated': 'Profile updated',
    'account.profileUpdateSuccess': 'Your display name has been updated successfully.',
    'account.profileUpdateError': 'Failed to update profile. Please try again.',
    'account.signedOut': 'Signed out',
    'account.signedOutSuccess': 'You have been signed out successfully.',
    'account.photoUploadSoon': 'Profile photo upload will be available soon!',
    'account.emailChangeNote': 'Email changes require verification and will be available soon',
    'account.contactSupport': 'Contact Support',
    'account.deletionRequest': 'Please email us at support@ayahwallpapers.com for account deletion requests.',
    
    // Appearance Settings
    'appearance.theme': 'Theme',
    'appearance.themeSystem': 'System',
    'appearance.themeLight': 'Light',
    'appearance.themeDark': 'Dark',
    'appearance.fontSize': 'Text Size',
    'appearance.fontSizeSmall': 'Small',
    'appearance.fontSizeMedium': 'Medium (Default)',
    'appearance.fontSizeLarge': 'Large',
    'appearance.fontSizeExtraLarge': 'Extra Large',
    'appearance.selectFontSize': 'Select font size',
    'appearance.previewText': 'Preview: Sample text in {size} size - Lorem ipsum dolor sit amet',
    'appearance.updated': 'Appearance updated',
    
    // Daily Verse Settings
    'daily.title': 'Daily Verse Settings',
    'daily.signInNote': 'Sign in to save your daily verse preferences and sync across devices.',
    'daily.updates': 'Daily Verse Updates',
    'daily.updatesDesc': 'Automatically get a new verse each day',
    'daily.updateTime': 'Daily Update Time',
    'daily.updateTimeDesc': 'Choose when to receive your daily verse',
    'daily.selectTime': 'Select time',
    'daily.autoWallpaper': 'Auto Wallpaper Download',
    'daily.autoWallpaperDesc': 'Automatically download new wallpapers for easy setup',
    'daily.notifications': 'Daily Verse Notifications',
    'daily.notificationsDesc': 'Get notified when your daily verse is ready',
    'daily.frequency': 'Update Frequency',
    'daily.frequencyDesc': 'How often to automatically refresh your verses',
    'daily.daily': 'Daily',
    'daily.weekly': 'Weekly',
    'daily.manual': 'Manual Only',
    'daily.selectFrequency': 'Select frequency',
    'daily.settingUpdated': 'Setting updated',
    
    // Notification Settings
    'notifications.title': 'Notifications',
    'notifications.signInNote': 'Sign in to save your notification preferences across devices.',
    'notifications.enablePush': 'Enable Push Notifications',
    'notifications.enablePushDesc': 'Allow notifications to receive daily verse reminders',
    'notifications.enable': 'Enable',
    'notifications.enabled': 'Notifications enabled',
    'notifications.enabledDesc': 'You\'ll now receive notifications for daily verses and updates.',
    'notifications.blocked': 'Notifications blocked',
    'notifications.blockedDesc': 'Please enable notifications in your browser settings to receive updates.',
    'notifications.notSupported': 'Not supported',
    'notifications.notSupportedDesc': 'Your browser doesn\'t support notifications.',
    'notifications.updated': 'Settings Updated',
    'notifications.settingEnabled': 'Setting enabled successfully',
    'notifications.settingUpdated': 'Setting updated successfully',
    'notifications.permissionGranted': 'Notifications enabled',
    'notifications.permissionGrantedDesc': 'You\'ll now receive notifications for daily verses and updates.',
    'notifications.permissionBlocked': 'Notifications blocked',
    'notifications.permissionBlockedDesc': 'Please enable notifications in your browser settings to receive updates.',
    'notifications.dailyReminders': 'Daily Verse Reminders',
    'notifications.dailyRemindersDesc': 'Get notified when new verses are available',
    'notifications.reminderTime': 'Reminder Time',
    'notifications.selectTime': 'Select notification time',
    'notifications.time6amFajr': '6:00 AM - Fajr',
    'notifications.time7amMorning': '7:00 AM - Morning',
    'notifications.time12pmDhuhr': '12:00 PM - Dhuhr',
    'notifications.time3pmAsr': '3:00 PM - Asr',
    'notifications.time6pmMaghrib': '6:00 PM - Maghrib',
    'notifications.time8pmIsha': '8:00 PM - Isha',
    'notifications.time9pmEvening': '9:00 PM - Evening',
    'notifications.prayerReminders': 'Prayer Time Reminders',
    'notifications.prayerRemindersDesc': 'Get notifications for prayer times with verses',
    'notifications.features': 'New Features & Updates',
    'notifications.featuresDesc': 'Be notified about new app features and improvements',
    'notifications.sound': 'Sound & Vibration',
    'notifications.soundEnabled': 'Notification Sound',
    'notifications.soundEnabledDesc': 'Play sound for notifications',
    'notifications.vibration': 'Vibration',
    'notifications.vibrationDesc': 'Vibrate on mobile devices',
    'notifications.soundSelect': 'Notification Sound',
    'notifications.selectSound': 'Select notification sound',
    'notifications.soundDefault': 'Default',
    'notifications.soundAdhan': 'Adhan Call',
    'notifications.soundChime': 'Gentle Chime',
    'notifications.soundBell': 'Bell',
    'notifications.soundSilent': 'Silent',
    'notifications.quietHours': 'Quiet Hours',
    'notifications.quietHoursDesc': 'Disable notifications during specified hours',
    
    // Widget Settings
    'widget.title': 'Home Screen Widget',
    'widget.configured': 'Widget Configured',
    'widget.configuredDesc': 'Your widget settings have been saved successfully',
    'widget.installation': 'Widget Installation',
    'widget.installationDesc': 'Follow the instructions below to add the widget to your home screen',
    'widget.preview': 'Widget Preview',
    'widget.todayVerse': 'Today\'s Verse',
    'widget.enable': 'Enable Widget',
    'widget.enableDesc': 'Add a beautiful widget to your home screen',
    'widget.size': 'Widget Size',
    'widget.selectSize': 'Select widget size',
    'widget.sizeSmall': 'Small (2x2)',
    'widget.sizeMedium': 'Medium (4x2)', 
    'widget.sizeLarge': 'Large (4x4)',
    'widget.frequency': 'Update Frequency',
    'widget.selectFrequency': 'Select update frequency',
    'widget.frequencyDaily': 'Daily',
    'widget.frequencyTwice': 'Twice Daily',
    'widget.frequencyHourly': 'Hourly',
    'widget.frequencyNote': 'How often the widget content should refresh',
    'widget.theme': 'Widget Theme',
    'widget.selectTheme': 'Select theme',
    'widget.themeClassic': 'Classic',
    'widget.themeMinimal': 'Minimal',
    'widget.themeElegant': 'Elegant',
    'widget.content': 'Content Settings',
    'widget.showArabic': 'Show Arabic Text',
    'widget.showArabicDesc': 'Display original Arabic verse text',
    'widget.showTranslation': 'Show Translation',
    'widget.showTranslationDesc': 'Display translated verse text',
    'widget.saveConfig': 'Save Configuration',
    'widget.installWidget': 'Install Widget',
    'widget.instructionsTitle': 'Installation Instructions',
    'widget.instructionsIOS': 'Press and hold on home screen, tap "+", search for "Ayah Wallpapers", select widget size',
    'widget.instructionsAndroid': 'Long press on home screen, select "Widgets", find "Ayah Wallpapers", drag to position',
    'widget.tip': 'Tip: Make sure the app is installed and configured before adding the widget',
    
    // Data Privacy Settings
    'privacy.title': 'Data & Privacy',
    'privacy.signInRequired': 'Sign in required',
    'privacy.signInToSync': 'Please sign in to sync your data across devices',
    'privacy.signInToExport': 'Please sign in to export your data',
    'privacy.syncSuccess': 'Data synced successfully',
    'privacy.syncSuccessDesc': 'Your settings and data are now synchronized across all devices',
    'privacy.syncFailed': 'Sync failed',
    'privacy.syncFailedDesc': 'Failed to sync data. Please try again later',
    'privacy.cacheCleared': 'Cache cleared',
    'privacy.cacheClearedDesc': 'Temporary files and cache have been cleared successfully',
    'privacy.cacheClearError': 'Failed to clear cache. Please try again',
    'privacy.dataExported': 'Data exported',
    'privacy.dataExportedDesc': 'Your data has been downloaded as a JSON file',
    'privacy.dataSync': 'Data Synchronization',
    'privacy.dataSyncDesc': 'Sync your settings and favorites across devices',
    'privacy.dataSyncDisabled': 'Sign in to enable data sync',
    'privacy.enabled': 'Enabled',
    'privacy.disabled': 'Disabled',
    'privacy.lastSync': 'Last sync:',
    'privacy.syncNow': 'Sync Now',
    'privacy.syncing': 'Syncing...',
    'privacy.storage': 'Storage Usage',
    'privacy.used': 'Used:',
    'privacy.wallpapers': 'Wallpapers:',
    'privacy.settings': 'Settings:',
    'privacy.favorites': 'Favorites:',
    'privacy.cache': 'Cache:',
    'privacy.dataManagement': 'Data Management',
    'privacy.exportData': 'Export My Data',
    'privacy.clearCache': 'Clear Cache & Temporary Files',
    'privacy.clearingCache': 'Clearing Cache...',
    'privacy.privacyControls': 'Privacy Controls',
    'privacy.analytics': 'Anonymous Analytics',
    'privacy.analyticsDesc': 'Help improve the app by sharing anonymous usage data',
    'privacy.crashReports': 'Crash Reports',
    'privacy.crashReportsDesc': 'Send crash reports to help improve app stability',
    'privacy.legal': 'Legal & Policies',
    'privacy.comingSoon': 'Coming Soon',
    'privacy.policyComingSoon': 'Privacy policy will be available soon',
    'privacy.termsComingSoon': 'Terms of service will be available soon',
    'privacy.dataComingSoon': 'Data policy will be available soon',
    'privacy.privacyPolicy': 'Privacy Policy',
    'privacy.termsOfService': 'Terms of Service',
    'privacy.dataPolicy': 'Data Usage Policy',
    'privacy.dangerZone': 'Danger Zone',
    'privacy.deleteAccount': 'Delete Account',
    'privacy.deleteAccountDesc': 'Permanently delete your account and all associated data',
    'privacy.requestDeletion': 'Request Account Deletion',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.surah': 'Surah',
    'common.wallpaper': 'Wallpaper',
    
    // Customize
    'customize.title': 'Customize Wallpaper',
    'customize.subtitle': 'Create your perfect Islamic wallpaper design',
    'customize.livePreview': 'Live Preview',
    'customize.reset': 'Reset',
    'customize.generateHint': 'Generate a preview to see your design',
    'customize.generatePreview': 'Generate Preview',
    'customize.generating': 'Generating...',
    'customize.download': 'Download Wallpaper',
    'customize.regenerate': 'Regenerate',
    'customize.sectionTitle': 'Customize Your Wallpaper',
    'customize.resolution': 'Resolution',
    'customize.backgroundImages': 'Background Images',
    'customize.gradient': 'Gradient',
    'customize.hide': 'Hide',
    'customize.customize': 'Customize',
    'customize.showOriginal': 'Show Original',
    
    // Wallpaper
    'wallpaper.newVerse': 'New Verse',
    'wallpaper.downloaded': 'Wallpaper downloaded',
    'wallpaper.savedToDevice': 'Your beautiful Islamic wallpaper has been saved to your device',
    'wallpaper.generated': 'Wallpaper generated',
    'wallpaper.previewReady': 'Your custom wallpaper preview is ready!',
    'wallpaper.addedToFavorites': 'Added to favorites',
    'wallpaper.savedToFavorites': 'This verse has been saved to your favorites',
    'wallpaper.signInToSave': 'Please sign in to save favorites',
    
    // Favorites
    'favorites.subtitle': 'Your beloved Quranic verses',
    'favorites.noFavoritesYet': 'No favorites yet',
    'favorites.startBuilding': 'Start building your collection by adding verses to your favorites',
    'favorites.browseLibrary': 'Browse Library',
    'favorites.favoriteVerses': 'Favorite Verses',
    'favorites.added': 'Added',
    'favorites.createWallpaper': 'Create Wallpaper',
    'favorites.copiedToClipboard': 'Verse text has been copied to your clipboard',
    'favorites.shareNotSupported': 'Share not supported',
    'favorites.copyManually': 'Please copy the verse text manually',
  },
  
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.library': 'Bibliothèque',
    'nav.favorites': 'Favoris',
    'nav.customize': 'Personnaliser',
    'nav.settings': 'Paramètres',
    
    // Home page
    'home.title': 'Inspiration Islamique Quotidienne',
    'home.subtitle': 'Beaux versets coraniques en fond d\'écran',
    'home.todayVerse': 'Verset du jour',
    'home.generateWallpaper': 'Générer un fond d\'écran',
    'home.addToFavorites': 'Ajouter aux favoris',
    'home.removeFromFavorites': 'Retirer des favoris',
    'home.welcomeBack': 'Bon retour, {name}!',
    'home.signInCta': 'Connectez-vous pour enregistrer vos préférences',
    
    // Library
    'library.title': 'Bibliothèque de versets',
    'library.subtitle': 'Explorez notre collection de versets coraniques',
    'library.search': 'Rechercher des versets...',
    'library.filter': 'Filtrer par thème',
    'library.all': 'Tous',
    'library.share': 'Partager',
    'library.generateWallpaper': 'Générer un fond d\'écran',
    'library.noResults': 'Aucun verset ne correspond à vos critères',
    
    // Categories
    'categories.faith': 'Foi',
    'categories.wisdom': 'Sagesse',
    'categories.patience': 'Patience',
    'categories.forgiveness': 'Pardon',
    'categories.guidance': 'Orientation',
    'categories.comfort': 'Réconfort',
    'categories.gratitude': 'Gratitude',
    'categories.protection': 'Protection',
    'categories.trust': 'Confiance',
    'categories.power': 'Puissance',
    'categories.blessing': 'Bénédiction',
    
    // Settings
    'settings.title': 'Paramètres',
    'settings.subtitle': 'Personnalisez votre expérience Ayah Wallpaper',
    'settings.account': 'Compte',
    'settings.appearance': 'Apparence',
    'settings.language': 'Langue et localisation',
    'settings.notifications': 'Notifications',
    'settings.privacy': 'Données et confidentialité',
    
    // Language Settings
    'language.interfaceLanguage': 'Langue de l\'interface',
    'language.interfaceLanguageDesc': 'Choisissez votre langue préférée pour l\'interface de l\'application',
    'language.translationStyle': 'Style de traduction',
    'language.translationStyleDesc': 'Choisissez comment vous préférez que les versets coraniques soient traduits',
    'language.arabicTextSettings': 'Paramètres du texte arabe',
    'language.arabicTextSize': 'Taille du texte arabe',
    'language.regionalSettings': 'Paramètres régionaux',
    'language.dateFormat': 'Format de date',
    'language.timeFormat': 'Format d\'heure',
    'language.unsavedChanges': 'Vous avez des modifications non enregistrées',
    'language.discard': 'Abandonner',
    'language.saveChanges': 'Enregistrer les modifications',
    'language.saving': 'Enregistrement...',
    
    // Translation styles
    'translation.literal': 'Traduction littérale',
    'translation.interpretive': 'Traduction interprétative',
    'translation.simplified': 'Langage simplifié',
    
    // Date/Time formats
    'format.gregorian': 'Calendrier grégorien',
    'format.hijri': 'Calendrier hijri',
    'format.both': 'Les deux calendriers',
    'format.12h': '12 heures (AM/PM)',
    'format.24h': '24 heures',
    
    // Account
    'account.displayName': 'Nom d\'affichage',
    'account.email': 'Adresse e-mail',
    'account.verified': 'Vérifié',
    'account.signOut': 'Se déconnecter',
    'account.deleteAccount': 'Demander la suppression du compte',
    'account.profilePicture': 'Photo de profil',
    'account.profilePictureHint': 'Ajoutez une photo pour personnaliser votre compte',
    'account.enterDisplayName': 'Entrez votre nom d\'affichage',
    'account.noDisplayName': 'Aucun nom d\'affichage défini',
    'account.profileUpdated': 'Profil mis à jour',
    'account.profileUpdateSuccess': 'Votre nom d\'affichage a été mis à jour avec succès.',
    'account.profileUpdateError': 'Échec de la mise à jour du profil. Veuillez réessayer.',
    'account.signedOut': 'Déconnecté',
    'account.signedOutSuccess': 'Vous avez été déconnecté avec succès.',
    'account.photoUploadSoon': 'Le téléchargement de photos de profil sera bientôt disponible !',
    'account.emailChangeNote': 'Les changements d\'email nécessitent une vérification et seront bientôt disponibles',
    'account.contactSupport': 'Contacter le support',
    'account.deletionRequest': 'Veuillez nous envoyer un e-mail à support@ayahwallpapers.com pour les demandes de suppression de compte.',
    
    // Appearance Settings
    'appearance.theme': 'Thème',
    'appearance.themeSystem': 'Système',
    'appearance.themeLight': 'Clair',
    'appearance.themeDark': 'Sombre',
    'appearance.fontSize': 'Taille du texte',
    'appearance.fontSizeSmall': 'Petit',
    'appearance.fontSizeMedium': 'Moyen (par défaut)',
    'appearance.fontSizeLarge': 'Grand',
    'appearance.fontSizeExtraLarge': 'Très grand',
    'appearance.selectFontSize': 'Sélectionner la taille de police',
    'appearance.previewText': 'Aperçu : Texte d\'exemple en taille {size} - Lorem ipsum dolor sit amet',
    'appearance.updated': 'Apparence mise à jour',
    
    // Daily Verse Settings
    'daily.title': 'Paramètres du verset quotidien',
    'daily.signInNote': 'Connectez-vous pour enregistrer vos préférences de verset quotidien et synchroniser sur tous les appareils.',
    'daily.updates': 'Mises à jour du verset quotidien',
    'daily.updatesDesc': 'Obtenez automatiquement un nouveau verset chaque jour',
    'daily.updateTime': 'Heure de mise à jour quotidienne',
    'daily.updateTimeDesc': 'Choisissez quand recevoir votre verset quotidien',
    'daily.selectTime': 'Sélectionner l\'heure',
    'daily.autoWallpaper': 'Téléchargement automatique de fond d\'écran',
    'daily.autoWallpaperDesc': 'Téléchargez automatiquement de nouveaux fonds d\'écran pour un réglage facile',
    'daily.notifications': 'Notifications de verset quotidien',
    'daily.notificationsDesc': 'Soyez averti lorsque votre verset quotidien est prêt',
    'daily.frequency': 'Fréquence de mise à jour',
    'daily.frequencyDesc': 'À quelle fréquence mettre à jour automatiquement vos versets',
    'daily.daily': 'Quotidien',
    'daily.weekly': 'Hebdomadaire',
    'daily.manual': 'Manuel uniquement',
    'daily.selectFrequency': 'Sélectionner la fréquence',
    'daily.settingUpdated': 'Paramètre mis à jour',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.signInNote': 'Connectez-vous pour enregistrer vos préférences de notification sur tous les appareils.',
    'notifications.enablePush': 'Activer les notifications push',
    'notifications.enablePushDesc': 'Autoriser les notifications pour recevoir les rappels de versets quotidiens',
    'notifications.enable': 'Activer',
    'notifications.enabled': 'Notifications activées',
    'notifications.enabledDesc': 'Vous recevrez maintenant des notifications pour les versets quotidiens et les mises à jour.',
    'notifications.blocked': 'Notifications bloquées',
    'notifications.blockedDesc': 'Veuillez activer les notifications dans les paramètres de votre navigateur pour recevoir les mises à jour.',
    'notifications.notSupported': 'Non pris en charge',
    'notifications.notSupportedDesc': 'Votre navigateur ne prend pas en charge les notifications.',
    'notifications.updated': 'Paramètres mis à jour',
    'notifications.settingEnabled': 'Paramètre activé avec succès',
    'notifications.settingUpdated': 'Paramètre mis à jour avec succès',
    'notifications.permissionGranted': 'Notifications activées',
    'notifications.permissionGrantedDesc': 'Vous recevrez maintenant des notifications pour les versets quotidiens et les mises à jour.',
    'notifications.permissionBlocked': 'Notifications bloquées',
    'notifications.permissionBlockedDesc': 'Veuillez activer les notifications dans les paramètres de votre navigateur pour recevoir les mises à jour.',
    'notifications.dailyReminders': 'Rappels de versets quotidiens',
    'notifications.dailyRemindersDesc': 'Être notifié lorsque de nouveaux versets sont disponibles',
    'notifications.reminderTime': 'Heure du rappel',
    'notifications.selectTime': 'Sélectionner l\'heure de notification',
    'notifications.time6amFajr': '6h00 - Fajr',
    'notifications.time7amMorning': '7h00 - Matin',
    'notifications.time12pmDhuhr': '12h00 - Dhuhr',
    'notifications.time3pmAsr': '15h00 - Asr',
    'notifications.time6pmMaghrib': '18h00 - Maghrib',
    'notifications.time8pmIsha': '20h00 - Isha',
    'notifications.time9pmEvening': '21h00 - Soir',
    'notifications.prayerReminders': 'Rappels d\'heures de prière',
    'notifications.prayerRemindersDesc': 'Recevoir des notifications pour les heures de prière avec des versets',
    'notifications.features': 'Nouvelles fonctionnalités et mises à jour',
    'notifications.featuresDesc': 'Être notifié des nouvelles fonctionnalités de l\'application et des améliorations',
    'notifications.sound': 'Son et vibration',
    'notifications.soundEnabled': 'Son de notification',
    'notifications.soundEnabledDesc': 'Jouer un son pour les notifications',
    'notifications.vibration': 'Vibration',
    'notifications.vibrationDesc': 'Vibrer sur les appareils mobiles',
    'notifications.soundSelect': 'Son de notification',
    'notifications.selectSound': 'Sélectionner le son de notification',
    'notifications.soundDefault': 'Par défaut',
    'notifications.soundAdhan': 'Appel à la prière',
    'notifications.soundChime': 'Carillon doux',
    'notifications.soundBell': 'Cloche',
    'notifications.soundSilent': 'Silencieux',
    'notifications.quietHours': 'Heures silencieuses',
    'notifications.quietHoursDesc': 'Désactiver les notifications pendant les heures spécifiées',

    // Widget Settings
    'widget.title': 'Widget d\'écran d\'accueil',
    'widget.configured': 'Widget configuré',
    'widget.configuredDesc': 'Vos paramètres de widget ont été enregistrés avec succès',
    'widget.installation': 'Installation du widget',
    'widget.installationDesc': 'Suivez les instructions ci-dessous pour ajouter le widget à votre écran d\'accueil',
    'widget.preview': 'Aperçu du widget',
    'widget.todayVerse': 'Verset du jour',
    'widget.enable': 'Activer le widget',
    'widget.enableDesc': 'Ajouter un beau widget à votre écran d\'accueil',
    'widget.size': 'Taille du widget',
    'widget.selectSize': 'Sélectionner la taille du widget',
    'widget.sizeSmall': 'Petit (2x2)',
    'widget.sizeMedium': 'Moyen (4x2)',
    'widget.sizeLarge': 'Grand (4x4)',
    'widget.frequency': 'Fréquence de mise à jour',
    'widget.selectFrequency': 'Sélectionner la fréquence de mise à jour',
    'widget.frequencyDaily': 'Quotidien',
    'widget.frequencyTwice': 'Deux fois par jour',
    'widget.frequencyHourly': 'Toutes les heures',
    'widget.frequencyNote': 'À quelle fréquence le contenu du widget doit se rafraîchir',
    'widget.theme': 'Thème du widget',
    'widget.selectTheme': 'Sélectionner le thème',
    'widget.themeClassic': 'Classique',
    'widget.themeMinimal': 'Minimal',
    'widget.themeElegant': 'Élégant',
    'widget.content': 'Paramètres de contenu',
    'widget.showArabic': 'Afficher le texte arabe',
    'widget.showArabicDesc': 'Afficher le texte original du verset en arabe',
    'widget.showTranslation': 'Afficher la traduction',
    'widget.showTranslationDesc': 'Afficher le texte traduit du verset',
    'widget.saveConfig': 'Enregistrer la configuration',
    'widget.installWidget': 'Installer le widget',
    'widget.instructionsTitle': 'Instructions d\'installation',
    'widget.instructionsIOS': 'Maintenez enfoncé sur l\'écran d\'accueil, appuyez sur "+", recherchez "Ayah Wallpapers", sélectionnez la taille du widget',
    'widget.instructionsAndroid': 'Appui long sur l\'écran d\'accueil, sélectionnez "Widgets", trouvez "Ayah Wallpapers", glissez vers la position',
    'widget.tip': 'Astuce : Assurez-vous que l\'application est installée et configurée avant d\'ajouter le widget',
    
    // Data Privacy Settings
    'privacy.title': 'Données et confidentialité',
    'privacy.signInRequired': 'Connexion requise',
    'privacy.signInToSync': 'Veuillez vous connecter pour synchroniser vos données sur tous les appareils',
    'privacy.signInToExport': 'Veuillez vous connecter pour exporter vos données',
    'privacy.syncSuccess': 'Données synchronisées avec succès',
    'privacy.syncSuccessDesc': 'Vos paramètres et données sont maintenant synchronisés sur tous les appareils',
    'privacy.syncFailed': 'Échec de la synchronisation',
    'privacy.syncFailedDesc': 'Échec de la synchronisation des données. Veuillez réessayer plus tard',
    'privacy.cacheCleared': 'Cache vidé',
    'privacy.cacheClearedDesc': 'Les fichiers temporaires et le cache ont été effacés avec succès',
    'privacy.cacheClearError': 'Échec de la suppression du cache. Veuillez réessayer',
    'privacy.dataExported': 'Données exportées',
    'privacy.dataExportedDesc': 'Vos données ont été téléchargées sous forme de fichier JSON',
    'privacy.dataSync': 'Synchronisation des données',
    'privacy.dataSyncDesc': 'Synchronisez vos paramètres et favoris sur tous les appareils',
    'privacy.dataSyncDisabled': 'Connectez-vous pour activer la synchronisation des données',
    'privacy.enabled': 'Activé',
    'privacy.disabled': 'Désactivé',
    'privacy.lastSync': 'Dernière synchronisation :',
    'privacy.syncNow': 'Synchroniser maintenant',
    'privacy.syncing': 'Synchronisation...',
    'privacy.storage': 'Utilisation du stockage',
    'privacy.used': 'Utilisé :',
    'privacy.wallpapers': 'Fonds d\'écran :',
    'privacy.settings': 'Paramètres :',
    'privacy.favorites': 'Favoris :',
    'privacy.cache': 'Cache :',
    'privacy.dataManagement': 'Gestion des données',
    'privacy.exportData': 'Exporter mes données',
    'privacy.clearCache': 'Vider le cache et les fichiers temporaires',
    'privacy.clearingCache': 'Suppression du cache...',
    'privacy.privacyControls': 'Contrôles de confidentialité',
    'privacy.analytics': 'Analyses anonymes',
    'privacy.analyticsDesc': 'Aidez à améliorer l\'application en partageant des données d\'utilisation anonymes',
    'privacy.crashReports': 'Rapports de plantage',
    'privacy.crashReportsDesc': 'Envoyer des rapports de plantage pour aider à améliorer la stabilité de l\'application',
    'privacy.legal': 'Légal et politiques',
    'privacy.comingSoon': 'Bientôt disponible',
    'privacy.policyComingSoon': 'La politique de confidentialité sera bientôt disponible',
    'privacy.termsComingSoon': 'Les conditions d\'utilisation seront bientôt disponibles',
    'privacy.dataComingSoon': 'La politique de données sera bientôt disponible',
    'privacy.privacyPolicy': 'Politique de confidentialité',
    'privacy.termsOfService': 'Conditions d\'utilisation',
    'privacy.dataPolicy': 'Politique d\'utilisation des données',
    'privacy.dangerZone': 'Zone de danger',
    'privacy.deleteAccount': 'Supprimer le compte',
    'privacy.deleteAccountDesc': 'Supprimer définitivement votre compte et toutes les données associées',
    'privacy.requestDeletion': 'Demander la suppression du compte',
    
    // Common
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.surah': 'Sourate',
    'common.wallpaper': 'Fond',
    
    // Personnaliser
    'customize.title': 'Personnaliser le fond d\'écran',
    'customize.subtitle': 'Créez votre design parfait de fond d\'écran islamique',
    'customize.livePreview': 'Aperçu en direct',
    'customize.reset': 'Réinitialiser',
    'customize.generateHint': 'Générez un aperçu pour voir votre design',
    'customize.generatePreview': 'Générer l\'aperçu',
    'customize.generating': 'Génération...',
    'customize.download': 'Télécharger le fond d\'écran',
    'customize.regenerate': 'Régénérer',
    'customize.sectionTitle': 'Personnalisez votre fond',
    'customize.resolution': 'Résolution',
    'customize.backgroundImages': 'Images de fond',
    'customize.gradient': 'Dégradé',
    'customize.hide': 'Masquer',
    'customize.customize': 'Personnaliser',
    'customize.showOriginal': 'Voir l\'original',
    
    // Fond d'écran
    'wallpaper.newVerse': 'Nouveau verset',
    'wallpaper.downloaded': 'Fond téléchargé',
    'wallpaper.savedToDevice': 'Votre beau fond islamique a été enregistré sur votre appareil',
    'wallpaper.generated': 'Fond généré',
    'wallpaper.previewReady': 'Votre aperçu personnalisé est prêt !',
    'wallpaper.addedToFavorites': 'Ajouté aux favoris',
    'wallpaper.savedToFavorites': 'Ce verset a été enregistré dans vos favoris',
    'wallpaper.signInToSave': 'Veuillez vous connecter pour enregistrer les favoris',
    
    // Favoris
    'favorites.subtitle': 'Vos versets coraniques préférés',
    'favorites.noFavoritesYet': 'Aucun favori pour le moment',
    'favorites.startBuilding': 'Commencez à constituer votre collection en ajoutant des versets à vos favoris',
    'favorites.browseLibrary': 'Parcourir la bibliothèque',
    'favorites.favoriteVerses': 'Versets favoris',
    'favorites.added': 'Ajouté',
    'favorites.createWallpaper': 'Créer un fond',
    'favorites.copiedToClipboard': 'Le texte du verset a été copié dans votre presse-papiers',
    'favorites.shareNotSupported': 'Partage non pris en charge',
    'favorites.copyManually': 'Veuillez copier le texte du verset manuellement',
  },
  
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.library': 'المكتبة',
    'nav.favorites': 'المفضلة',
    'nav.customize': 'تخصيص',
    'nav.settings': 'الإعدادات',
    
    // Home page
    'home.title': 'الإلهام الإسلامي اليومي',
    'home.subtitle': 'آيات قرآنية جميلة كخلفيات',
    'home.todayVerse': 'آية اليوم',
    'home.generateWallpaper': 'إنشاء خلفية',
    'home.addToFavorites': 'إضافة إلى المفضلة',
    'home.removeFromFavorites': 'إزالة من المفضلة',
    'home.welcomeBack': 'مرحبًا بعودتك، {name}!',
    'home.signInCta': 'سجّل الدخول لحفظ تفضيلاتك',
    
    // Library
    'library.title': 'مكتبة الآيات',
    'library.subtitle': 'استكشف مجموعتنا من الآيات القرآنية',
    'library.search': 'البحث في الآيات...',
    'library.filter': 'تصفية حسب الموضوع',
    'library.all': 'الكل',
    'library.share': 'مشاركة',
    'library.generateWallpaper': 'إنشاء خلفية',
    'library.noResults': 'لا توجد آيات تطابق معايير البحث',
    
    // Categories
    'categories.faith': 'الإيمان',
    'categories.wisdom': 'الحكمة',
    'categories.patience': 'الصبر',
    'categories.forgiveness': 'المغفرة',
    'categories.guidance': 'الهداية',
    'categories.comfort': 'الراحة',
    'categories.gratitude': 'الشكر',
    'categories.protection': 'الحماية',
    'categories.trust': 'الثقة',
    'categories.power': 'القوة',
    'categories.blessing': 'البركة',
    
    // Settings
    'settings.title': 'الإعدادات',
    'settings.subtitle': 'خصص تجربتك مع خلفيات الآيات',
    'settings.account': 'الحساب',
    'settings.appearance': 'المظهر',
    'settings.language': 'اللغة والتوطين',
    'settings.notifications': 'الإشعارات',
    'settings.privacy': 'البيانات والخصوصية',
    
    // Language Settings
    'language.interfaceLanguage': 'لغة الواجهة',
    'language.interfaceLanguageDesc': 'اختر لغتك المفضلة لواجهة التطبيق',
    'language.translationStyle': 'نمط الترجمة',
    'language.translationStyleDesc': 'اختر كيف تفضل ترجمة الآيات القرآنية',
    'language.arabicTextSettings': 'إعدادات النص العربي',
    'language.arabicTextSize': 'حجم النص العربي',
    'language.regionalSettings': 'الإعدادات الإقليمية',
    'language.dateFormat': 'تنسيق التاريخ',
    'language.timeFormat': 'تنسيق الوقت',
    'language.unsavedChanges': 'لديك تغييرات غير محفوظة',
    'language.discard': 'تجاهل',
    'language.saveChanges': 'حفظ التغييرات',
    'language.saving': 'جاري الحفظ...',
    
    // Translation styles
    'translation.literal': 'ترجمة حرفية',
    'translation.interpretive': 'ترجمة تفسيرية',
    'translation.simplified': 'لغة مبسطة',
    
    // Date/Time formats
    'format.gregorian': 'التقويم الميلادي',
    'format.hijri': 'التقويم الهجري',
    'format.both': 'كلا التقويمين',
    'format.12h': '12 ساعة (ص/م)',
    'format.24h': '24 ساعة',
    
    // Account
    'account.displayName': 'اسم العرض',
    'account.email': 'عنوان البريد الإلكتروني',
    'account.verified': 'مُتحقق منه',
    'account.signOut': 'تسجيل الخروج',
    'account.deleteAccount': 'طلب حذف الحساب',
    'account.profilePicture': 'صورة الملف الشخصي',
    'account.profilePictureHint': 'أضف صورة لتخصيص حسابك',
    'account.enterDisplayName': 'أدخل اسم العرض الخاص بك',
    'account.noDisplayName': 'لم يتم تعيين اسم عرض',
    'account.profileUpdated': 'تم تحديث الملف الشخصي',
    'account.profileUpdateSuccess': 'تم تحديث اسم العرض بنجاح.',
    'account.profileUpdateError': 'فشل في تحديث الملف الشخصي. يرجى المحاولة مرة أخرى.',
    'account.signedOut': 'تم تسجيل الخروج',
    'account.signedOutSuccess': 'تم تسجيل خروجك بنجاح.',
    'account.photoUploadSoon': 'سيتوفر رفع صورة الملف الشخصي قريباً!',
    'account.emailChangeNote': 'تتطلب تغييرات البريد الإلكتروني التحقق وستكون متاحة قريباً',
    'account.contactSupport': 'اتصل بالدعم',
    'account.deletionRequest': 'يرجى مراسلتنا على support@ayahwallpapers.com لطلبات حذف الحساب.',
    
    // Appearance Settings
    'appearance.theme': 'المظهر',
    'appearance.themeSystem': 'النظام',
    'appearance.themeLight': 'فاتح',
    'appearance.themeDark': 'داكن',
    'appearance.fontSize': 'حجم النص',
    'appearance.fontSizeSmall': 'صغير',
    'appearance.fontSizeMedium': 'متوسط (افتراضي)',
    'appearance.fontSizeLarge': 'كبير',
    'appearance.fontSizeExtraLarge': 'كبير جداً',
    'appearance.selectFontSize': 'اختر حجم الخط',
    'appearance.previewText': 'معاينة: نص تجريبي بحجم {size} - النص التجريبي هنا',
    'appearance.updated': 'تم تحديث المظهر',
    
    // Daily Verse Settings
    'daily.title': 'إعدادات الآية اليومية',
    'daily.signInNote': 'سجل الدخول لحفظ تفضيلات الآية اليومية والمزامنة عبر الأجهزة.',
    'daily.updates': 'تحديثات الآية اليومية',
    'daily.updatesDesc': 'احصل تلقائياً على آية جديدة كل يوم',
    'daily.updateTime': 'وقت التحديث اليومي',
    'daily.updateTimeDesc': 'اختر متى تريد تلقي آيتك اليومية',
    'daily.selectTime': 'اختر الوقت',
    'daily.autoWallpaper': 'تنزيل الخلفية تلقائياً',
    'daily.autoWallpaperDesc': 'تنزيل خلفيات جديدة تلقائياً للإعداد السهل',
    'daily.notifications': 'إشعارات الآية اليومية',
    'daily.notificationsDesc': 'احصل على إشعار عندما تكون آيتك اليومية جاهزة',
    'daily.frequency': 'تكرار التحديث',
    'daily.frequencyDesc': 'كم مرة يتم تحديث آياتك تلقائياً',
    'daily.daily': 'يومياً',
    'daily.weekly': 'أسبوعياً',
    'daily.manual': 'يدوي فقط',
    'daily.selectFrequency': 'اختر التكرار',
    'daily.settingUpdated': 'تم تحديث الإعداد',
    
    // Notifications
    'notifications.title': 'الإشعارات',
    'notifications.signInNote': 'سجل الدخول لحفظ إعدادات الإشعارات على جميع الأجهزة.',
    'notifications.enablePush': 'تفعيل الإشعارات الفورية',
    'notifications.enablePushDesc': 'السماح بالإشعارات لتلقي تذكيرات الآيات اليومية',
    'notifications.enable': 'تفعيل',
    'notifications.enabled': 'تم تفعيل الإشعارات',
    'notifications.enabledDesc': 'ستتلقى الآن إشعارات للآيات اليومية والتحديثات.',
    'notifications.blocked': 'الإشعارات محظورة',
    'notifications.blockedDesc': 'يرجى تفعيل الإشعارات في إعدادات المتصفح لتلقي التحديثات.',
    'notifications.notSupported': 'غير مدعوم',
    'notifications.notSupportedDesc': 'متصفحك لا يدعم الإشعارات.',
    'notifications.updated': 'تم تحديث الإعدادات',
    'notifications.settingEnabled': 'تم تفعيل الإعداد بنجاح',
    'notifications.settingUpdated': 'تم تحديث الإعداد بنجاح',
    'notifications.permissionGranted': 'تم تفعيل الإشعارات',
    'notifications.permissionGrantedDesc': 'ستتلقى الآن إشعارات للآيات اليومية والتحديثات.',
    'notifications.permissionBlocked': 'الإشعارات محظورة',
    'notifications.permissionBlockedDesc': 'يرجى تفعيل الإشعارات في إعدادات المتصفح لتلقي التحديثات.',
    'notifications.dailyReminders': 'تذكيرات الآيات اليومية',
    'notifications.dailyRemindersDesc': 'تلقي إشعارات عند توفر آيات جديدة',
    'notifications.reminderTime': 'وقت التذكير',
    'notifications.selectTime': 'اختر وقت الإشعار',
    'notifications.time6amFajr': '6:00 ص - الفجر',
    'notifications.time7amMorning': '7:00 ص - الصباح',
    'notifications.time12pmDhuhr': '12:00 م - الظهر',
    'notifications.time3pmAsr': '3:00 م - العصر',
    'notifications.time6pmMaghrib': '6:00 م - المغرب',
    'notifications.time8pmIsha': '8:00 م - العشاء',
    'notifications.time9pmEvening': '9:00 م - المساء',
    'notifications.prayerReminders': 'تذكيرات أوقات الصلاة',
    'notifications.prayerRemindersDesc': 'تلقي إشعارات لأوقات الصلاة مع الآيات',
    'notifications.features': 'الميزات الجديدة والتحديثات',
    'notifications.featuresDesc': 'تلقي إشعارات حول ميزات التطبيق الجديدة والتحسينات',
    'notifications.sound': 'الصوت والاهتزاز',
    'notifications.soundEnabled': 'صوت الإشعار',
    'notifications.soundEnabledDesc': 'تشغيل صوت للإشعارات',
    'notifications.vibration': 'الاهتزاز',
    'notifications.vibrationDesc': 'اهتزاز على الأجهزة المحمولة',
    'notifications.soundSelect': 'صوت الإشعار',
    'notifications.selectSound': 'اختر صوت الإشعار',
    'notifications.soundDefault': 'افتراضي',
    'notifications.soundAdhan': 'نداء الصلاة',
    'notifications.soundChime': 'جرس لطيف',
    'notifications.soundBell': 'جرس',
    'notifications.soundSilent': 'صامت',
    'notifications.quietHours': 'ساعات الصمت',
    'notifications.quietHoursDesc': 'إيقاف الإشعارات خلال الساعات المحددة',

    // Widget Settings
    'widget.title': 'ويدجت الشاشة الرئيسية',
    'widget.configured': 'تم تكوين الويدجت',
    'widget.configuredDesc': 'تم حفظ إعدادات الويدجت بنجاح',
    'widget.installation': 'تثبيت الويدجت',
    'widget.installationDesc': 'اتبع التعليمات أدناه لإضافة الويدجت إلى شاشتك الرئيسية',
    'widget.preview': 'معاينة الويدجت',
    'widget.todayVerse': 'آية اليوم',
    'widget.enable': 'تفعيل الويدجت',
    'widget.enableDesc': 'إضافة ويدجت جميل إلى شاشتك الرئيسية',
    'widget.size': 'حجم الويدجت',
    'widget.selectSize': 'اختر حجم الويدجت',
    'widget.sizeSmall': 'صغير (2x2)',
    'widget.sizeMedium': 'متوسط (4x2)',
    'widget.sizeLarge': 'كبير (4x4)',
    'widget.frequency': 'تكرار التحديث',
    'widget.selectFrequency': 'اختر تكرار التحديث',
    'widget.frequencyDaily': 'يومياً',
    'widget.frequencyTwice': 'مرتان يومياً',
    'widget.frequencyHourly': 'كل ساعة',
    'widget.frequencyNote': 'كم مرة يجب تحديث محتوى الويدجت',
    'widget.theme': 'موضوع الويدجت',
    'widget.selectTheme': 'اختر الموضوع',
    'widget.themeClassic': 'كلاسيكي',
    'widget.themeMinimal': 'بسيط',
    'widget.themeElegant': 'أنيق',
    'widget.content': 'إعدادات المحتوى',
    'widget.showArabic': 'إظهار النص العربي',
    'widget.showArabicDesc': 'عرض نص الآية الأصلي بالعربية',
    'widget.showTranslation': 'إظهار الترجمة',
    'widget.showTranslationDesc': 'عرض نص الآية المترجم',
    'widget.saveConfig': 'حفظ التكوين',
    'widget.installWidget': 'تثبيت الويدجت',
    'widget.instructionsTitle': 'تعليمات التثبيت',
    'widget.instructionsIOS': 'اضغط مع الاستمرار على الشاشة الرئيسية، اضغط على "+"، ابحث عن "Ayah Wallpapers"، اختر حجم الويدجت',
    'widget.instructionsAndroid': 'اضغط لفترة طويلة على الشاشة الرئيسية، اختر "Widgets"، ابحث عن "Ayah Wallpapers"، اسحب إلى الموضع',
    'widget.tip': 'نصيحة: تأكد من تثبيت التطبيق وتكوينه قبل إضافة الويدجت',
    
    // Data Privacy Settings
    'privacy.title': 'البيانات والخصوصية',
    'privacy.signInRequired': 'يجب تسجيل الدخول',
    'privacy.signInToSync': 'يرجى تسجيل الدخول لمزامنة بياناتك عبر الأجهزة',
    'privacy.signInToExport': 'يرجى تسجيل الدخول لتصدير بياناتك',
    'privacy.syncSuccess': 'تم مزامنة البيانات بنجاح',
    'privacy.syncSuccessDesc': 'إعداداتك وبياناتك الآن متزامنة عبر جميع الأجهزة',
    'privacy.syncFailed': 'فشل في المزامنة',
    'privacy.syncFailedDesc': 'فشل في مزامنة البيانات. يرجى المحاولة مرة أخرى لاحقاً',
    'privacy.cacheCleared': 'تم مسح التخزين المؤقت',
    'privacy.cacheClearedDesc': 'تم مسح الملفات المؤقتة والتخزين المؤقت بنجاح',
    'privacy.cacheClearError': 'فشل في مسح التخزين المؤقت. يرجى المحاولة مرة أخرى',
    'privacy.dataExported': 'تم تصدير البيانات',
    'privacy.dataExportedDesc': 'تم تنزيل بياناتك كملف JSON',
    'privacy.dataSync': 'مزامنة البيانات',
    'privacy.dataSyncDesc': 'مزامنة إعداداتك ومفضلاتك عبر الأجهزة',
    'privacy.dataSyncDisabled': 'سجل الدخول لتفعيل مزامنة البيانات',
    'privacy.enabled': 'مفعّل',
    'privacy.disabled': 'معطّل',
    'privacy.lastSync': 'آخر مزامنة:',
    'privacy.syncNow': 'مزامنة الآن',
    'privacy.syncing': 'جاري المزامنة...',
    'privacy.storage': 'استخدام التخزين',
    'privacy.used': 'مُستخدم:',
    'privacy.wallpapers': 'الخلفيات:',
    'privacy.settings': 'الإعدادات:',
    'privacy.favorites': 'المفضلة:',
    'privacy.cache': 'التخزين المؤقت:',
    'privacy.dataManagement': 'إدارة البيانات',
    'privacy.exportData': 'تصدير بياناتي',
    'privacy.clearCache': 'مسح التخزين المؤقت والملفات المؤقتة',
    'privacy.clearingCache': 'جاري مسح التخزين المؤقت...',
    'privacy.privacyControls': 'ضوابط الخصوصية',
    'privacy.analytics': 'التحليلات المجهولة',
    'privacy.analyticsDesc': 'ساعد في تحسين التطبيق بمشاركة بيانات الاستخدام المجهولة',
    'privacy.crashReports': 'تقارير الأخطاء',
    'privacy.crashReportsDesc': 'إرسال تقارير الأخطاء للمساعدة في تحسين استقرار التطبيق',
    'privacy.legal': 'القانونية والسياسات',
    'privacy.comingSoon': 'قريباً',
    'privacy.policyComingSoon': 'سياسة الخصوصية ستكون متاحة قريباً',
    'privacy.termsComingSoon': 'شروط الخدمة ستكون متاحة قريباً',
    'privacy.dataComingSoon': 'سياسة البيانات ستكون متاحة قريباً',
    'privacy.privacyPolicy': 'سياسة الخصوصية',
    'privacy.termsOfService': 'شروط الخدمة',
    'privacy.dataPolicy': 'سياسة استخدام البيانات',
    'privacy.dangerZone': 'منطقة الخطر',
    'privacy.deleteAccount': 'حذف الحساب',
    'privacy.deleteAccountDesc': 'حذف حسابك وجميع البيانات المرتبطة به نهائياً',
    'privacy.requestDeletion': 'طلب حذف الحساب',
    
    // Common
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجح',
    'common.surah': 'سورة',
    'common.wallpaper': 'خلفية',
    
    // تخصيص
    'customize.title': 'تخصيص الخلفية',
    'customize.subtitle': 'أنشئ تصميم الخلفية الإسلامية المثالية',
    'customize.livePreview': 'معاينة مباشرة',
    'customize.reset': 'إعادة تعيين',
    'customize.generateHint': 'أنشئ معاينة لرؤية تصميمك',
    'customize.generatePreview': 'إنشاء معاينة',
    'customize.generating': 'جاري الإنشاء...',
    'customize.download': 'تنزيل الخلفية',
    'customize.regenerate': 'إعادة إنشاء',
    'customize.sectionTitle': 'خصص خلفيتك',
    'customize.resolution': 'الدقة',
    'customize.backgroundImages': 'صور الخلفية',
    'customize.gradient': 'التدرج',
    'customize.hide': 'إخفاء',
    'customize.customize': 'تخصيص',
    'customize.showOriginal': 'إظهار الأصل',
    
    // خلفية
    'wallpaper.newVerse': 'آية جديدة',
    'wallpaper.downloaded': 'تم تنزيل الخلفية',
    'wallpaper.savedToDevice': 'تم حفظ خلفيتك الإسلامية الجميلة على جهازك',
    'wallpaper.generated': 'تم إنشاء الخلفية',
    'wallpaper.previewReady': 'معاينة خلفيتك المخصصة جاهزة!',
    'wallpaper.addedToFavorites': 'تمت الإضافة للمفضلة',
    'wallpaper.savedToFavorites': 'تم حفظ هذه الآية في مفضلاتك',
    'wallpaper.signInToSave': 'يرجى تسجيل الدخول لحفظ المفضلة',
    
    // المفضلة
    'favorites.subtitle': 'آياتك القرآنية المحبوبة',
    'favorites.noFavoritesYet': 'لا توجد مفضلة بعد',
    'favorites.startBuilding': 'ابدأ في بناء مجموعتك بإضافة الآيات إلى مفضلاتك',
    'favorites.browseLibrary': 'تصفح المكتبة',
    'favorites.favoriteVerses': 'الآيات المفضلة',
    'favorites.added': 'تمت الإضافة',
    'favorites.createWallpaper': 'إنشاء خلفية',
    'favorites.copiedToClipboard': 'تم نسخ نص الآية إلى الحافظة',
    'favorites.shareNotSupported': 'المشاركة غير مدعومة',
    'favorites.copyManually': 'يرجى نسخ نص الآية يدوياً',
  },
  
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.library': 'Biblioteca',
    'nav.favorites': 'Favoritos',
    'nav.customize': 'Personalizar',
    'nav.settings': 'Configuración',
    
    // Home page
    'home.title': 'Inspiración Islámica Diaria',
    'home.subtitle': 'Hermosos versos coránicos como fondos de pantalla',
    'home.todayVerse': 'Verso de hoy',
    'home.generateWallpaper': 'Generar fondo de pantalla',
    'home.addToFavorites': 'Añadir a favoritos',
    'home.removeFromFavorites': 'Eliminar de favoritos',
    'home.welcomeBack': '¡Bienvenido de nuevo, {name}!',
    'home.signInCta': 'Inicia sesión para guardar tus preferencias',
    
    // Library
    'library.title': 'Biblioteca de versos',
    'library.subtitle': 'Explora nuestra colección de versos coránicos',
    'library.search': 'Buscar versos...',
    'library.filter': 'Filtrar por tema',
    'library.all': 'Todos',
    'library.share': 'Compartir',
    'library.generateWallpaper': 'Generar fondo de pantalla',
    'library.noResults': 'No hay versos que coincidan con tus criterios de búsqueda',
    
    // Categories
    'categories.faith': 'Fe',
    'categories.wisdom': 'Sabiduría',
    'categories.patience': 'Paciencia',
    'categories.forgiveness': 'Perdón',
    'categories.guidance': 'Guía',
    'categories.comfort': 'Consuelo',
    'categories.gratitude': 'Gratitud',
    'categories.protection': 'Protección',
    'categories.trust': 'Confianza',
    'categories.power': 'Poder',
    'categories.blessing': 'Bendición',
    
    // Settings
    'settings.title': 'Configuración',
    'settings.subtitle': 'Personaliza tu experiencia con Ayah Wallpaper',
    'settings.account': 'Cuenta',
    'settings.appearance': 'Apariencia',
    'settings.language': 'Idioma y localización',
    'settings.notifications': 'Notificaciones',
    'settings.privacy': 'Datos y privacidad',
    
    // Language Settings
    'language.interfaceLanguage': 'Idioma de la interfaz',
    'language.interfaceLanguageDesc': 'Elige tu idioma preferido para la interfaz de la aplicación',
    'language.translationStyle': 'Estilo de traducción',
    'language.translationStyleDesc': 'Elige cómo prefieres que se traduzcan los versos coránicos',
    'language.arabicTextSettings': 'Configuración del texto árabe',
    'language.arabicTextSize': 'Tamaño del texto árabe',
    'language.regionalSettings': 'Configuración regional',
    'language.dateFormat': 'Formato de fecha',
    'language.timeFormat': 'Formato de hora',
    'language.unsavedChanges': 'Tienes cambios no guardados',
    'language.discard': 'Descartar',
    'language.saveChanges': 'Guardar cambios',
    'language.saving': 'Guardando...',
    
    // Translation styles
    'translation.literal': 'Traducción literal',
    'translation.interpretive': 'Traducción interpretativa',
    'translation.simplified': 'Lenguaje simplificado',
    
    // Date/Time formats
    'format.gregorian': 'Calendario gregoriano',
    'format.hijri': 'Calendario hijri',
    'format.both': 'Ambos calendarios',
    'format.12h': '12 horas (AM/PM)',
    'format.24h': '24 horas',
    
    // Account
    'account.displayName': 'Nombre para mostrar',
    'account.email': 'Dirección de correo electrónico',
    'account.verified': 'Verificado',
    'account.signOut': 'Cerrar sesión',
    'account.deleteAccount': 'Solicitar eliminación de cuenta',
    'account.profilePicture': 'Foto de perfil',
    'account.profilePictureHint': 'Agrega una foto para personalizar tu cuenta',
    'account.enterDisplayName': 'Ingresa tu nombre para mostrar',
    'account.noDisplayName': 'No se ha establecido nombre para mostrar',
    'account.profileUpdated': 'Perfil actualizado',
    'account.profileUpdateSuccess': 'Tu nombre para mostrar se ha actualizado correctamente.',
    'account.profileUpdateError': 'Error al actualizar el perfil. Inténtalo de nuevo.',
    'account.signedOut': 'Sesión cerrada',
    'account.signedOutSuccess': 'Has cerrado sesión correctamente.',
    'account.photoUploadSoon': '¡La subida de foto de perfil estará disponible pronto!',
    'account.emailChangeNote': 'Los cambios de correo electrónico requieren verificación y estarán disponibles pronto',
    'account.contactSupport': 'Contactar soporte',
    'account.deletionRequest': 'Envíanos un correo a support@ayahwallpapers.com para solicitudes de eliminación de cuenta.',
    
    // Appearance Settings
    'appearance.theme': 'Tema',
    'appearance.themeSystem': 'Sistema',
    'appearance.themeLight': 'Claro',
    'appearance.themeDark': 'Oscuro',
    'appearance.fontSize': 'Tamaño de texto',
    'appearance.fontSizeSmall': 'Pequeño',
    'appearance.fontSizeMedium': 'Mediano (predeterminado)',
    'appearance.fontSizeLarge': 'Grande',
    'appearance.fontSizeExtraLarge': 'Extra grande',
    'appearance.selectFontSize': 'Seleccionar tamaño de fuente',
    'appearance.previewText': 'Vista previa: Texto de muestra en tamaño {size} - Lorem ipsum dolor sit amet',
    'appearance.updated': 'Apariencia actualizada',
    
    // Daily Verse Settings
    'daily.title': 'Configuración de verso diario',
    'daily.signInNote': 'Inicia sesión para guardar tus preferencias de verso diario y sincronizar en todos los dispositivos.',
    'daily.updates': 'Actualizaciones de verso diario',
    'daily.updatesDesc': 'Obtener automáticamente un nuevo verso cada día',
    'daily.updateTime': 'Hora de actualización diaria',
    'daily.updateTimeDesc': 'Elige cuándo recibir tu verso diario',
    'daily.selectTime': 'Seleccionar hora',
    'daily.autoWallpaper': 'Descarga automática de fondo de pantalla',
    'daily.autoWallpaperDesc': 'Descargar automáticamente nuevos fondos de pantalla para una configuración fácil',
    'daily.notifications': 'Notificaciones de verso diario',
    'daily.notificationsDesc': 'Recibir notificaciones cuando tu verso diario esté listo',
    'daily.frequency': 'Frecuencia de actualización',
    'daily.frequencyDesc': 'Con qué frecuencia actualizar automáticamente tus versos',
    'daily.daily': 'Diario',
    'daily.weekly': 'Semanal',
    'daily.manual': 'Solo manual',
    'daily.selectFrequency': 'Seleccionar frecuencia',
    'daily.settingUpdated': 'Configuración actualizada',
    
    // Notifications
    'notifications.title': 'Notificaciones',
    'notifications.signInNote': 'Inicia sesión para guardar tus preferencias de notificación en todos los dispositivos.',
    'notifications.enablePush': 'Habilitar notificaciones push',
    'notifications.enablePushDesc': 'Permitir notificaciones para recibir recordatorios de versos diarios',
    'notifications.enable': 'Habilitar',
    'notifications.enabled': 'Notificaciones habilitadas',
    'notifications.enabledDesc': 'Ahora recibirás notificaciones para versos diarios y actualizaciones.',
    'notifications.blocked': 'Notificaciones bloqueadas',
    'notifications.blockedDesc': 'Por favor habilita las notificaciones en la configuración de tu navegador para recibir actualizaciones.',
    'notifications.notSupported': 'No compatible',
    'notifications.notSupportedDesc': 'Tu navegador no soporta notificaciones.',
    'notifications.updated': 'Configuración actualizada',
    'notifications.settingEnabled': 'Configuración habilitada exitosamente',
    'notifications.settingUpdated': 'Configuración actualizada exitosamente',
    'notifications.permissionGranted': 'Notificaciones habilitadas',
    'notifications.permissionGrantedDesc': 'Ahora recibirás notificaciones para versos diarios y actualizaciones.',
    'notifications.permissionBlocked': 'Notificaciones bloqueadas',
    'notifications.permissionBlockedDesc': 'Por favor habilita las notificaciones en la configuración de tu navegador para recibir actualizaciones.',
    'notifications.dailyReminders': 'Recordatorios de versos diarios',
    'notifications.dailyRemindersDesc': 'Recibir notificaciones cuando nuevos versos estén disponibles',
    'notifications.reminderTime': 'Hora de recordatorio',
    'notifications.selectTime': 'Seleccionar hora de notificación',
    'notifications.time6amFajr': '6:00 AM - Fajr',
    'notifications.time7amMorning': '7:00 AM - Mañana',
    'notifications.time12pmDhuhr': '12:00 PM - Dhuhr',
    'notifications.time3pmAsr': '3:00 PM - Asr',
    'notifications.time6pmMaghrib': '6:00 PM - Maghrib',
    'notifications.time8pmIsha': '8:00 PM - Isha',
    'notifications.time9pmEvening': '9:00 PM - Noche',
    'notifications.prayerReminders': 'Recordatorios de horarios de oración',
    'notifications.prayerRemindersDesc': 'Recibir notificaciones para horarios de oración con versos',
    'notifications.features': 'Nuevas características y actualizaciones',
    'notifications.featuresDesc': 'Ser notificado sobre nuevas características de la aplicación y mejoras',
    'notifications.sound': 'Sonido y vibración',
    'notifications.soundEnabled': 'Sonido de notificación',
    'notifications.soundEnabledDesc': 'Reproducir sonido para notificaciones',
    'notifications.vibration': 'Vibración',
    'notifications.vibrationDesc': 'Vibrar en dispositivos móviles',
    'notifications.soundSelect': 'Sonido de notificación',
    'notifications.selectSound': 'Seleccionar sonido de notificación',
    'notifications.soundDefault': 'Predeterminado',
    'notifications.soundAdhan': 'Llamada a la oración',
    'notifications.soundChime': 'Campana suave',
    'notifications.soundBell': 'Campana',
    'notifications.soundSilent': 'Silencioso',
    'notifications.quietHours': 'Horas silenciosas',
    'notifications.quietHoursDesc': 'Deshabilitar notificaciones durante las horas especificadas',

    // Widget Settings
    'widget.title': 'Widget de pantalla de inicio',
    'widget.configured': 'Widget configurado',
    'widget.configuredDesc': 'La configuración de tu widget se ha guardado exitosamente',
    'widget.installation': 'Instalación de widget',
    'widget.installationDesc': 'Sigue las instrucciones a continuación para agregar el widget a tu pantalla de inicio',
    'widget.preview': 'Vista previa del widget',
    'widget.todayVerse': 'Verso de hoy',
    'widget.enable': 'Habilitar widget',
    'widget.enableDesc': 'Agregar un hermoso widget a tu pantalla de inicio',
    'widget.size': 'Tamaño del widget',
    'widget.selectSize': 'Seleccionar tamaño del widget',
    'widget.sizeSmall': 'Pequeño (2x2)',
    'widget.sizeMedium': 'Mediano (4x2)',
    'widget.sizeLarge': 'Grande (4x4)',
    'widget.frequency': 'Frecuencia de actualización',
    'widget.selectFrequency': 'Seleccionar frecuencia de actualización',
    'widget.frequencyDaily': 'Diario',
    'widget.frequencyTwice': 'Dos veces al día',
    'widget.frequencyHourly': 'Cada hora',
    'widget.frequencyNote': 'Con qué frecuencia debe actualizarse el contenido del widget',
    'widget.theme': 'Tema del widget',
    'widget.selectTheme': 'Seleccionar tema',
    'widget.themeClassic': 'Clásico',
    'widget.themeMinimal': 'Minimalista',
    'widget.themeElegant': 'Elegante',
    'widget.content': 'Configuración de contenido',
    'widget.showArabic': 'Mostrar texto árabe',
    'widget.showArabicDesc': 'Mostrar el texto original del verso en árabe',
    'widget.showTranslation': 'Mostrar traducción',
    'widget.showTranslationDesc': 'Mostrar el texto traducido del verso',
    'widget.saveConfig': 'Guardar configuración',
    'widget.installWidget': 'Instalar widget',
    'widget.instructionsTitle': 'Instrucciones de instalación',
    'widget.instructionsIOS': 'Mantén presionado en la pantalla de inicio, toca "+", busca "Ayah Wallpapers", selecciona el tamaño del widget',
    'widget.instructionsAndroid': 'Presiona prolongadamente en la pantalla de inicio, selecciona "Widgets", encuentra "Ayah Wallpapers", arrastra a la posición',
    'widget.tip': 'Consejo: Asegúrate de que la aplicación esté instalada y configurada antes de agregar el widget',
    
    // Data Privacy Settings
    'privacy.title': 'Datos y privacidad',
    'privacy.signInRequired': 'Inicio de sesión requerido',
    'privacy.signInToSync': 'Por favor inicia sesión para sincronizar tus datos en todos los dispositivos',
    'privacy.signInToExport': 'Por favor inicia sesión para exportar tus datos',
    'privacy.syncSuccess': 'Datos sincronizados exitosamente',
    'privacy.syncSuccessDesc': 'Tus configuraciones y datos ahora están sincronizados en todos los dispositivos',
    'privacy.syncFailed': 'Falló la sincronización',
    'privacy.syncFailedDesc': 'Error al sincronizar datos. Por favor inténtalo de nuevo más tarde',
    'privacy.cacheCleared': 'Caché eliminado',
    'privacy.cacheClearedDesc': 'Los archivos temporales y el caché se han eliminado exitosamente',
    'privacy.cacheClearError': 'Error al eliminar el caché. Por favor inténtalo de nuevo',
    'privacy.dataExported': 'Datos exportados',
    'privacy.dataExportedDesc': 'Tus datos se han descargado como archivo JSON',
    'privacy.dataSync': 'Sincronización de datos',
    'privacy.dataSyncDesc': 'Sincroniza tus configuraciones y favoritos en todos los dispositivos',
    'privacy.dataSyncDisabled': 'Inicia sesión para habilitar la sincronización de datos',
    'privacy.enabled': 'Habilitado',
    'privacy.disabled': 'Deshabilitado',
    'privacy.lastSync': 'Última sincronización:',
    'privacy.syncNow': 'Sincronizar ahora',
    'privacy.syncing': 'Sincronizando...',
    'privacy.storage': 'Uso de almacenamiento',
    'privacy.used': 'Usado:',
    'privacy.wallpapers': 'Fondos de pantalla:',
    'privacy.settings': 'Configuraciones:',
    'privacy.favorites': 'Favoritos:',
    'privacy.cache': 'Caché:',
    'privacy.dataManagement': 'Gestión de datos',
    'privacy.exportData': 'Exportar mis datos',
    'privacy.clearCache': 'Eliminar caché y archivos temporales',
    'privacy.clearingCache': 'Eliminando caché...',
    'privacy.privacyControls': 'Controles de privacidad',
    'privacy.analytics': 'Análisis anónimo',
    'privacy.analyticsDesc': 'Ayuda a mejorar la aplicación compartiendo datos de uso anónimos',
    'privacy.crashReports': 'Informes de fallos',
    'privacy.crashReportsDesc': 'Enviar informes de fallos para ayudar a mejorar la estabilidad de la aplicación',
    'privacy.legal': 'Legal y políticas',
    'privacy.comingSoon': 'Próximamente',
    'privacy.policyComingSoon': 'La política de privacidad estará disponible pronto',
    'privacy.termsComingSoon': 'Los términos de servicio estarán disponibles pronto',
    'privacy.dataComingSoon': 'La política de datos estará disponible pronto',
    'privacy.privacyPolicy': 'Política de privacidad',
    'privacy.termsOfService': 'Términos de servicio',
    'privacy.dataPolicy': 'Política de uso de datos',
    'privacy.dangerZone': 'Zona de peligro',
    'privacy.deleteAccount': 'Eliminar cuenta',
    'privacy.deleteAccountDesc': 'Eliminar permanentemente tu cuenta y todos los datos asociados',
    'privacy.requestDeletion': 'Solicitar eliminación de cuenta',
    
    // Common
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.surah': 'Sura',
    'common.wallpaper': 'Fondo',
    
    // Personalizar
    'customize.title': 'Personalizar fondo de pantalla',
    'customize.subtitle': 'Crea tu diseño perfecto de fondo de pantalla islámico',
    'customize.livePreview': 'Vista previa en vivo',
    'customize.reset': 'Restablecer',
    'customize.generateHint': 'Genera una vista previa para ver tu diseño',
    'customize.generatePreview': 'Generar vista previa',
    'customize.generating': 'Generando...',
    'customize.download': 'Descargar fondo de pantalla',
    'customize.regenerate': 'Regenerar',
    'customize.sectionTitle': 'Personaliza tu fondo de pantalla',
    'customize.resolution': 'Resolución',
    'customize.backgroundImages': 'Imágenes de fondo',
    'customize.gradient': 'Gradiente',
    'customize.hide': 'Ocultar',
    'customize.customize': 'Personalizar',
    'customize.showOriginal': 'Mostrar original',
    
    // Fondo de pantalla
    'wallpaper.newVerse': 'Nuevo verso',
    'wallpaper.downloaded': 'Fondo de pantalla descargado',
    'wallpaper.savedToDevice': 'Tu hermoso fondo de pantalla islámico se ha guardado en tu dispositivo',
    'wallpaper.generated': 'Fondo de pantalla generado',
    'wallpaper.previewReady': '¡Tu vista previa personalizada del fondo de pantalla está lista!',
    'wallpaper.addedToFavorites': 'Añadido a favoritos',
    'wallpaper.savedToFavorites': 'Este verso se ha guardado en tus favoritos',
    'wallpaper.signInToSave': 'Por favor inicia sesión para guardar favoritos',
    
    // Favoritos
    'favorites.subtitle': 'Tus versos coránicos queridos',
    'favorites.noFavoritesYet': 'Aún no hay favoritos',
    'favorites.startBuilding': 'Comienza a construir tu colección agregando versos a tus favoritos',
    'favorites.browseLibrary': 'Explorar biblioteca',
    'favorites.favoriteVerses': 'Versos favoritos',
    'favorites.added': 'Añadido',
    'favorites.createWallpaper': 'Crear fondo de pantalla',
    'favorites.copiedToClipboard': 'El texto del verso se ha copiado al portapapeles',
    'favorites.shareNotSupported': 'Compartir no compatible',
    'favorites.copyManually': 'Por favor copia el texto del verso manualmente',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const stored = localStorage.getItem('language');
    return (stored as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string, fallback?: string) => {
    return translations[language][key] || fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};