// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gatxeplorffzrepiwkdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhdHhlcGxvcmZmenJlcGl3a2R6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NDk3OTEsImV4cCI6MjA3NDMyNTc5MX0.lCVemo4bd5Kkiu3iZrxfDaBCiOZCIBvfm1YyfpNj36Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});